// packages/vue/src/components/Newline.tsx
import { defineComponent, type PropType } from 'vue'
import { renderNewline } from '@wolfie/shared'
import { wNodeToVue } from '../wnode/wnode-to-vue'

//#region Types
export interface NewlineProps {
	/**
	 * Number of newlines to insert.
	 * @default 1
	 */
	count?: number
}
//#endregion Types

/**
 * Adds one or more newline (`\n`) characters. Must be used within `<Text>` components.
 */
export const Newline = defineComponent({
	name: 'Newline',
	props: {
		count: {
			type: Number as PropType<number>,
			default: 1,
		},
	},
	setup(props) {
		return () => wNodeToVue(renderNewline({ count: props.count ?? 1 }))
	},
})

export type { NewlineProps as Props, NewlineProps as IProps }

// packages/angular/src/components/newline/newline.component.ts
import {
	Component,
	Input,
	computed,
	ChangeDetectionStrategy,
} from '@angular/core'
import { renderNewline } from '@wolfie/shared'
import { WNodeOutletComponent } from '../wnode-outlet/wnode-outlet.component'

//#region NewlineComponent
/**
 * `<w-newline>` adds one or more empty lines between components
 */
@Component({
	selector: 'w-newline',
	standalone: true,
	imports: [WNodeOutletComponent],
	template: `<w-wnode-outlet [node]="wnode()" />`,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NewlineComponent {
	@Input() count = 1

	protected readonly wnode = computed(() =>
		renderNewline({ count: this.count })
	)
}
//#endregion NewlineComponent
