// examples/svelte_showcase/src/App.svelte
<!-- #region Script -->
<script lang="ts">
	import { Box, Text, useInput } from '@wolf-tui/svelte'

	//#region Screens
	import TimerDemo from './demos/TimerDemo.svelte'
	import TreeViewDemo from './demos/TreeViewDemo.svelte'
	import ComboboxDemo from './demos/ComboboxDemo.svelte'
	import JsonViewerDemo from './demos/JsonViewerDemo.svelte'
	import FilePickerDemo from './demos/FilePickerDemo.svelte'
	import BigTextDemo from './demos/BigTextDemo.svelte'
	import TableDemo from './demos/TableDemo.svelte'
	import ScrollViewDemo from './demos/ScrollViewDemo.svelte'
	import GradientDemo from './demos/GradientDemo.svelte'
	//#endregion Screens

	//#region Menu Data
	type DemoName =
		| 'timer'
		| 'treeview'
		| 'combobox'
		| 'jsonviewer'
		| 'filepicker'
		| 'bigtext'
		| 'table'
		| 'scrollview'
		| 'gradient'

	const DEMOS: Array<{ key: DemoName; label: string }> = [
		{ key: 'timer', label: 'Timer / Countdown / Stopwatch' },
		{ key: 'treeview', label: 'TreeView' },
		{ key: 'combobox', label: 'Combobox (Autocomplete)' },
		{ key: 'jsonviewer', label: 'JsonViewer' },
		{ key: 'filepicker', label: 'FilePicker' },
		{ key: 'bigtext', label: 'BigText (cfonts)' },
		{ key: 'table', label: 'Table' },
		{ key: 'scrollview', label: 'ScrollView' },
		{ key: 'gradient', label: 'Gradient (ink-gradient port)' },
	]
	//#endregion Menu Data

	//#region State
	let activeDemo = $state<DemoName | null>(null)
	let focused = $state(0)
	//#endregion State

	//#region Input
	function goBack() {
		activeDemo = null
	}

	useInput((_input, key) => {
		if (activeDemo !== null) return
		if (key.downArrow) focused = Math.min(focused + 1, DEMOS.length - 1)
		if (key.upArrow) focused = Math.max(focused - 1, 0)
		if (key.return) {
			const demo = DEMOS[focused]
			if (demo) activeDemo = demo.key
		}
	})
	//#endregion Input
</script>
<!-- #endregion Script -->

<!-- #region Template -->
{#if activeDemo === 'timer'}
	<TimerDemo onBack={goBack} />
{:else if activeDemo === 'treeview'}
	<TreeViewDemo onBack={goBack} />
{:else if activeDemo === 'combobox'}
	<ComboboxDemo onBack={goBack} />
{:else if activeDemo === 'jsonviewer'}
	<JsonViewerDemo onBack={goBack} />
{:else if activeDemo === 'filepicker'}
	<FilePickerDemo onBack={goBack} />
{:else if activeDemo === 'bigtext'}
	<BigTextDemo onBack={goBack} />
{:else if activeDemo === 'table'}
	<TableDemo onBack={goBack} />
{:else if activeDemo === 'scrollview'}
	<ScrollViewDemo onBack={goBack} />
{:else if activeDemo === 'gradient'}
	<GradientDemo onBack={goBack} />
{:else}
	<Box style={{ flexDirection: 'column', padding: 1 }}>
		<Text style={{ fontWeight: 'bold', color: 'cyan' }}>
			wolf-tui Community Components Showcase
		</Text>
		<Text style={{ dimColor: true }}>
			Use ↑↓ to navigate, Enter to select, Ctrl+C to exit
		</Text>
		<Box style={{ flexDirection: 'column', marginTop: 1 }}>
			{#each DEMOS as demo, i}
				<Text style={{ color: i === focused ? 'blue' : undefined }}>
					{i === focused ? '❯ ' : '  '}{demo.label}
				</Text>
			{/each}
		</Box>
	</Box>
{/if}
<!-- #endregion Template -->

// examples/vue_showcase/src/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Box, Text, useInput } from '@wolf-tui/vue'
import TimerDemo from './demos/TimerDemo.vue'
import TreeViewDemo from './demos/TreeViewDemo.vue'
import ComboboxDemo from './demos/ComboboxDemo.vue'
import JsonViewerDemo from './demos/JsonViewerDemo.vue'
import FilePickerDemo from './demos/FilePickerDemo.vue'
import BigTextDemo from './demos/BigTextDemo.vue'
import TableDemo from './demos/TableDemo.vue'
import ScrollViewDemo from './demos/ScrollViewDemo.vue'
import GradientDemo from './demos/GradientDemo.vue'

//#region Menu
type DemoName =
	| 'timer'
	| 'treeview'
	| 'combobox'
	| 'jsonviewer'
	| 'filepicker'
	| 'bigtext'
	| 'table'
	| 'scrollview'
	| 'gradient'

const DEMOS: Array<{ key: DemoName; label: string }> = [
	{ key: 'timer', label: 'Timer / Countdown / Stopwatch' },
	{ key: 'treeview', label: 'TreeView' },
	{ key: 'combobox', label: 'Combobox (Autocomplete)' },
	{ key: 'jsonviewer', label: 'JsonViewer' },
	{ key: 'filepicker', label: 'FilePicker' },
	{ key: 'bigtext', label: 'BigText (cfonts)' },
	{ key: 'table', label: 'Table' },
	{ key: 'scrollview', label: 'ScrollView' },
	{ key: 'gradient', label: 'Gradient (ink-gradient port)' },
]

const activeDemo = ref<DemoName | null>(null)
const focused = ref(0)

const showMenu = computed(() => activeDemo.value === null)

function handleBack() {
	activeDemo.value = null
}

useInput((_input, key) => {
	if (!showMenu.value) return
	if (key.downArrow)
		focused.value = Math.min(focused.value + 1, DEMOS.length - 1)
	if (key.upArrow) focused.value = Math.max(focused.value - 1, 0)
	if (key.return) activeDemo.value = DEMOS[focused.value]!.key
})
//#endregion Menu
</script>

<template>
	<!-- #region Demos -->
	<TimerDemo v-if="activeDemo === 'timer'" :on-back="handleBack" />
	<TreeViewDemo v-if="activeDemo === 'treeview'" :on-back="handleBack" />
	<ComboboxDemo v-if="activeDemo === 'combobox'" :on-back="handleBack" />
	<JsonViewerDemo v-if="activeDemo === 'jsonviewer'" :on-back="handleBack" />
	<FilePickerDemo v-if="activeDemo === 'filepicker'" :on-back="handleBack" />
	<BigTextDemo v-if="activeDemo === 'bigtext'" :on-back="handleBack" />
	<TableDemo v-if="activeDemo === 'table'" :on-back="handleBack" />
	<ScrollViewDemo v-if="activeDemo === 'scrollview'" :on-back="handleBack" />
	<GradientDemo v-if="activeDemo === 'gradient'" :on-back="handleBack" />
	<!-- #endregion Demos -->

	<!-- #region Menu -->
	<Box v-if="showMenu" :style="{ flexDirection: 'column', padding: 1 }">
		<Text :style="{ fontWeight: 'bold', color: 'cyan' }">
			wolf-tui Community Components Showcase
		</Text>
		<Text :style="{ dimColor: true }">
			Use arrow-keys to navigate, Enter to select, Ctrl+C to exit
		</Text>
		<Box :style="{ flexDirection: 'column', marginTop: 1 }">
			<Text
				v-for="(demo, i) in DEMOS"
				:key="demo.key"
				:style="{ color: i === focused ? 'blue' : undefined }"
			>
				{{ i === focused ? '> ' : '  ' }}{{ demo.label }}
			</Text>
		</Box>
	</Box>
	<!-- #endregion Menu -->
</template>
