// examples/angular_showcase/src/app.component.ts
import { Component, ChangeDetectionStrategy, signal } from '@angular/core'
import { BoxComponent, TextComponent, injectInput } from '@wolf-tui/angular'
import { TimerDemoComponent } from './demos/timer-demo.component'
import { TreeViewDemoComponent } from './demos/tree-view-demo.component'
import { ComboboxDemoComponent } from './demos/combobox-demo.component'
import { JsonViewerDemoComponent } from './demos/json-viewer-demo.component'
import { FilePickerDemoComponent } from './demos/file-picker-demo.component'
import { GradientDemoComponent } from './demos/gradient-demo.component'

//#region Types
type DemoName =
	| 'timer'
	| 'treeview'
	| 'combobox'
	| 'jsonviewer'
	| 'filepicker'
	| 'gradient'

interface IDemoEntry {
	key: DemoName
	label: string
}
//#endregion Types

//#region Constants
const DEMOS: ReadonlyArray<IDemoEntry> = [
	{ key: 'timer', label: 'Timer / Countdown / Stopwatch' },
	{ key: 'treeview', label: 'TreeView' },
	{ key: 'combobox', label: 'Combobox (Autocomplete)' },
	{ key: 'jsonviewer', label: 'JsonViewer' },
	{ key: 'filepicker', label: 'FilePicker' },
	{ key: 'gradient', label: 'Gradient (ink-gradient port)' },
]
//#endregion Constants

//#region AppComponent
@Component({
	selector: 'app-root',
	standalone: true,
	imports: [
		BoxComponent,
		TextComponent,
		TimerDemoComponent,
		TreeViewDemoComponent,
		ComboboxDemoComponent,
		JsonViewerDemoComponent,
		FilePickerDemoComponent,
		GradientDemoComponent,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		@switch (activeDemo()) {
			@case ('timer') {
				<app-timer-demo (back)="goBack()" />
			}
			@case ('treeview') {
				<app-tree-view-demo (back)="goBack()" />
			}
			@case ('combobox') {
				<app-combobox-demo (back)="goBack()" />
			}
			@case ('jsonviewer') {
				<app-json-viewer-demo (back)="goBack()" />
			}
			@case ('filepicker') {
				<app-file-picker-demo (back)="goBack()" />
			}
			@case ('gradient') {
				<app-gradient-demo (back)="goBack()" />
			}
			@default {
				<w-box [style]="{ flexDirection: 'column', padding: 1 }">
					<w-text [style]="{ fontWeight: 'bold', color: 'cyan' }">
						wolf-tui Community Components Showcase
					</w-text>
					<w-text [style]="{ dimColor: true }">
						Use arrow-keys to navigate, Enter to select, Ctrl+C to exit
					</w-text>
					<w-box [style]="{ flexDirection: 'column', marginTop: 1 }">
						@for (demo of demos; track demo.key; let i = $index) {
							<w-text [style]="{ color: i === focused() ? 'blue' : undefined }">
								{{ i === focused() ? '> ' : '  ' }}{{ demo.label }}
							</w-text>
						}
					</w-box>
				</w-box>
			}
		}
	`,
})
export class AppComponent {
	readonly demos = DEMOS
	readonly focused = signal(0)
	readonly activeDemo = signal<DemoName | null>(null)

	constructor() {
		injectInput((_input, key) => {
			if (this.activeDemo() !== null) return

			if (key.downArrow) {
				this.focused.update((f) => Math.min(f + 1, DEMOS.length - 1))
			}
			if (key.upArrow) {
				this.focused.update((f) => Math.max(f - 1, 0))
			}
			if (key.return) {
				const demo = DEMOS[this.focused()]
				if (demo) {
					this.activeDemo.set(demo.key)
				}
			}
		})
	}

	goBack(): void {
		this.activeDemo.set(null)
	}
}
//#endregion AppComponent

// examples/vue_showcase/src/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Box, Text, useInput } from '@wolf-tui/vue'
import TimerDemo from './demos/TimerDemo.vue'
import TreeViewDemo from './demos/TreeViewDemo.vue'
import ComboboxDemo from './demos/ComboboxDemo.vue'
import JsonViewerDemo from './demos/JsonViewerDemo.vue'
import FilePickerDemo from './demos/FilePickerDemo.vue'
import GradientDemo from './demos/GradientDemo.vue'

//#region Menu
type DemoName =
	| 'timer'
	| 'treeview'
	| 'combobox'
	| 'jsonviewer'
	| 'filepicker'
	| 'gradient'

const DEMOS: Array<{ key: DemoName; label: string }> = [
	{ key: 'timer', label: 'Timer / Countdown / Stopwatch' },
	{ key: 'treeview', label: 'TreeView' },
	{ key: 'combobox', label: 'Combobox (Autocomplete)' },
	{ key: 'jsonviewer', label: 'JsonViewer' },
	{ key: 'filepicker', label: 'FilePicker' },
	{ key: 'gradient', label: 'Gradient (ink-gradient port)' },
]

const activeDemo = ref<DemoName | null>(null)
const focused = ref(0)

const showMenu = computed(() => activeDemo.value === null)

function handleBack() {
	activeDemo.value = null
}

useInput((_input, key) => {
	if (!showMenu.value) return
	if (key.downArrow)
		focused.value = Math.min(focused.value + 1, DEMOS.length - 1)
	if (key.upArrow) focused.value = Math.max(focused.value - 1, 0)
	if (key.return) activeDemo.value = DEMOS[focused.value]!.key
})
//#endregion Menu
</script>

<template>
	<!-- #region Demos -->
	<TimerDemo v-if="activeDemo === 'timer'" :on-back="handleBack" />
	<TreeViewDemo v-if="activeDemo === 'treeview'" :on-back="handleBack" />
	<ComboboxDemo v-if="activeDemo === 'combobox'" :on-back="handleBack" />
	<JsonViewerDemo v-if="activeDemo === 'jsonviewer'" :on-back="handleBack" />
	<FilePickerDemo v-if="activeDemo === 'filepicker'" :on-back="handleBack" />
	<GradientDemo v-if="activeDemo === 'gradient'" :on-back="handleBack" />
	<!-- #endregion Demos -->

	<!-- #region Menu -->
	<Box v-if="showMenu" :style="{ flexDirection: 'column', padding: 1 }">
		<Text :style="{ fontWeight: 'bold', color: 'cyan' }">
			wolf-tui Community Components Showcase
		</Text>
		<Text :style="{ dimColor: true }">
			Use arrow-keys to navigate, Enter to select, Ctrl+C to exit
		</Text>
		<Box :style="{ flexDirection: 'column', marginTop: 1 }">
			<Text
				v-for="(demo, i) in DEMOS"
				:key="demo.key"
				:style="{ color: i === focused ? 'blue' : undefined }"
			>
				{{ i === focused ? '> ' : '  ' }}{{ demo.label }}
			</Text>
		</Box>
	</Box>
	<!-- #endregion Menu -->
</template>
