// packages/solid/src/components/Alert.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import {
	renderAlert,
	defaultAlertTheme,
	type AlertRenderTheme,
} from '@wolfie/shared'
import { useComponentTheme } from '../theme'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export type IAlertVariant = 'info' | 'success' | 'error' | 'warning'

export interface IAlertProps {
	children: JSX.Element
	variant: IAlertVariant
	title?: string
}
//#endregion Types

export function Alert(props: IAlertProps): JSX.Element {
	const [local] = splitProps(props, ['children', 'variant', 'title'])

	const theme = useComponentTheme<AlertRenderTheme>('Alert')
	const { styles, config } = theme ?? defaultAlertTheme

	// createMemo tracks reactive reads (local.variant, local.children) so the
	// WNode tree recomputes when props change.
	const wnode = createMemo(() =>
		renderAlert(
			{
				variant: local.variant,
				title: local.title,
				message: String(local.children ?? ''),
			},
			{ styles, config }
		)
	)

	// WHY: solid-js JSX.Element type = Node | ... (excludes () => JSX.Element in
	// this version). The function return IS valid at Solid runtime — insert() treats
	// () => Element as a reactive FunctionElement. Cast is safe.
	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}

// packages/svelte/src/components/Alert.svelte
<script lang="ts">
	import {
		renderAlert,
		defaultAlertTheme,
		type AlertRenderTheme,
	} from '@wolfie/shared'
	import { mountWNode } from '../wnode/wnode-to-svelte.js'
	import { useComponentTheme } from '../theme/index.js'

	//#region Types
	type AlertVariant = 'info' | 'success' | 'error' | 'warning'
	//#endregion Types

	let { variant, title, children }: {
		variant: AlertVariant
		title?: string
		children?: string
	} = $props()

	const theme = useComponentTheme<AlertRenderTheme>('Alert')
	const { styles, config } = theme ?? defaultAlertTheme

	let wnode = $derived(renderAlert(
		{ variant, title, message: String(children ?? '') },
		{ styles, config }
	))
</script>

<wolfie-box use:mountWNode={wnode}></wolfie-box>
