// packages/solid/src/components/StatusMessage.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import {
	renderStatusMessage,
	defaultStatusMessageTheme,
	type StatusMessageRenderTheme,
} from '@wolfie/shared'
import { useComponentTheme } from '../theme'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export type IStatusMessageVariant = 'info' | 'success' | 'error' | 'warning'

export interface IStatusMessageProps {
	children: JSX.Element
	variant: IStatusMessageVariant
}
//#endregion Types

export function StatusMessage(props: IStatusMessageProps): JSX.Element {
	const [local] = splitProps(props, ['children', 'variant'])

	const theme = useComponentTheme<StatusMessageRenderTheme>('StatusMessage')
	const { styles, config } = theme ?? defaultStatusMessageTheme

	const wnode = createMemo(() =>
		renderStatusMessage(
			{ variant: local.variant, message: String(local.children ?? '') },
			{ styles, config }
		)
	)

	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}

// packages/svelte/src/components/StatusMessage.svelte
<script lang="ts">
	import {
		renderStatusMessage,
		defaultStatusMessageTheme,
		type StatusMessageRenderTheme,
	} from '@wolfie/shared'
	import { mountWNode } from '../wnode/wnode-to-svelte.js'
	import { useComponentTheme } from '../theme/index.js'

	//#region Types
	type StatusMessageVariant = 'info' | 'success' | 'error' | 'warning'
	//#endregion Types

	let { variant, children }: {
		variant: StatusMessageVariant
		children?: string
	} = $props()

	const theme = useComponentTheme<StatusMessageRenderTheme>('StatusMessage')
	const { styles, config } = theme ?? defaultStatusMessageTheme

	let wnode = $derived(renderStatusMessage(
		{ variant, message: String(children ?? '') },
		{ styles, config }
	))
</script>

<wolfie-box use:mountWNode={wnode}></wolfie-box>
