// packages/solid/src/components/Text.tsx
import { useContext, Show, type JSX } from 'solid-js'
import chalk from 'chalk'
import { colorize, type Styles } from '@wolf-tui/core'
import { AccessibilityCtx, BackgroundCtx } from '../context/symbols'
import { resolveClassName, type ClassNameValue } from '../styles'

//#region Types
export interface TextProps {
	className?: ClassNameValue
	style?: Styles
	'aria-label'?: string
	'aria-hidden'?: boolean
	children?: JSX.Element
}
//#endregion Types

export function Text(props: TextProps) {
	const accessibility = useContext(AccessibilityCtx)
	const inheritedBackgroundColor = useContext(BackgroundCtx)

	// Accessor — re-evaluated on every access inside a reactive context.
	// WHY: IIFE pattern snapshots props once at mount; accessors let
	// Solid's reactivity trigger on prop changes (e.g. dynamic color).
	const effectiveStyles = (): Styles => {
		const resolved = resolveClassName(props.className)
		return { ...resolved, ...(props.style ?? {}) }
	}

	const transform = (text: string): string => {
		const styles = effectiveStyles()
		let result = text

		if (styles.color) {
			result = colorize(result, styles.color, 'foreground')
		}

		const finalBackgroundColor =
			styles.backgroundColor ?? inheritedBackgroundColor?.()
		if (finalBackgroundColor) {
			result = colorize(result, finalBackgroundColor, 'background')
		}

		if (styles.fontWeight === 'bold') result = chalk.bold(result)
		if (styles.fontStyle === 'italic') result = chalk.italic(result)
		if (styles.textDecoration === 'underline') result = chalk.underline(result)
		if (styles.textDecoration === 'line-through')
			result = chalk.strikethrough(result)
		if (styles.inverse ?? false) result = chalk.inverse(result)

		return result
	}

	const renderedChildren = () => {
		const isScreenReaderEnabled = accessibility?.isScreenReaderEnabled
		const ariaLabel = props['aria-label']
		return isScreenReaderEnabled && ariaLabel ? ariaLabel : props.children
	}

	const isHidden = () => {
		const isScreenReaderEnabled = accessibility?.isScreenReaderEnabled
		const ariaHidden = props['aria-hidden']
		if (isScreenReaderEnabled && ariaHidden) return true
		const children = renderedChildren()
		return children === undefined || children === null
	}

	return (
		<Show when={!isHidden()}>
			<wolfie-text
				style={{
					...effectiveStyles(),
					textWrap: effectiveStyles().textWrap ?? 'wrap',
				}}
				internal_transform={transform}
			>
				{renderedChildren()}
			</wolfie-text>
		</Show>
	)
}

export type { TextProps as Props, TextProps as IProps }

// packages/svelte/src/components/Text.svelte
<script lang="ts">
	import { getContext, type Snippet } from 'svelte'
	import chalk from 'chalk'
	import { colorize, type Styles } from '@wolfie/core'
	import { resolveClassName, type ClassNameValue } from '../styles/index.js'
	import { wolfieProps } from '../renderer/wolfie-action.js'
	import { ACCESSIBILITY_CTX, BACKGROUND_CTX } from '../context/symbols.js'
	import type { AccessibilityContextValue } from '../context/types.js'

	let {
		style,
		className,
		children,
		'aria-label': ariaLabel,
		'aria-hidden': ariaHidden,
	}: {
		style?: Styles
		className?: ClassNameValue
		children?: Snippet
		'aria-label'?: string
		'aria-hidden'?: boolean
	} = $props()

	const accessibility = getContext<AccessibilityContextValue | undefined>(ACCESSIBILITY_CTX)
	const inheritedBg = getContext<(() => string | undefined) | undefined>(BACKGROUND_CTX)

	let effectiveStyles = $derived({
		...resolveClassName(className),
		...(style ?? {}),
	} satisfies Styles)

	let effectiveWrap = $derived(effectiveStyles.textWrap ?? 'wrap')

	// Build the text transform function from current style props
	let transform = $derived.by((): ((text: string) => string) => {
		const effectiveColor = effectiveStyles.color
		const effectiveBackgroundColor = effectiveStyles.backgroundColor
		const effectiveBold = effectiveStyles.fontWeight === 'bold'
		const effectiveItalic = effectiveStyles.fontStyle === 'italic'
		const effectiveUnderline = effectiveStyles.textDecoration === 'underline'
		const effectiveStrikethrough = effectiveStyles.textDecoration === 'line-through'
		const effectiveInverse = effectiveStyles.inverse ?? false

		return (text: string): string => {
			let result = text

			if (effectiveColor) {
				result = colorize(result, effectiveColor, 'foreground')
			}

			const finalBg = effectiveBackgroundColor ?? inheritedBg?.()
			if (finalBg) {
				result = colorize(result, finalBg, 'background')
			}

			if (effectiveBold) result = chalk.bold(result)
			if (effectiveItalic) result = chalk.italic(result)
			if (effectiveUnderline) result = chalk.underline(result)
			if (effectiveStrikethrough) result = chalk.strikethrough(result)
			if (effectiveInverse) result = chalk.inverse(result)

			return result
		}
	})

	let isHidden = $derived(accessibility?.isScreenReaderEnabled && ariaHidden)
	let showAriaLabel = $derived(accessibility?.isScreenReaderEnabled && ariaLabel)
</script>

{#if !isHidden}
	{#if children || showAriaLabel}
		<wolfie-text
			use:wolfieProps={{ style: { ...effectiveStyles, textWrap: effectiveWrap }, internal_transform: transform }}
		>
			{#if showAriaLabel}
				{ariaLabel}
			{:else if children}
				{@render children()}
			{/if}
		</wolfie-text>
	{/if}
{/if}
