// examples/react_showcase/src/index.tsx
import { useState } from 'react'
import { render, Box, Text, useInput } from '@wolf-tui/react'
import { TimerDemo } from './demos/TimerDemo'
import { TreeViewDemo } from './demos/TreeViewDemo'
import { ComboboxDemo } from './demos/ComboboxDemo'
import { JsonViewerDemo } from './demos/JsonViewerDemo'
import { FilePickerDemo } from './demos/FilePickerDemo'
import { ScrollViewDemo } from './demos/ScrollViewDemo'
import { GradientDemo } from './demos/GradientDemo'

//#region Menu
type DemoName =
	| 'timer'
	| 'treeview'
	| 'combobox'
	| 'jsonviewer'
	| 'filepicker'
	| 'scrollview'
	| 'gradient'

const DEMOS: Array<{ key: DemoName; label: string }> = [
	{ key: 'timer', label: 'Timer / Countdown / Stopwatch' },
	{ key: 'treeview', label: 'TreeView' },
	{ key: 'combobox', label: 'Combobox (Autocomplete)' },
	{ key: 'jsonviewer', label: 'JsonViewer' },
	{ key: 'filepicker', label: 'FilePicker' },
	{ key: 'scrollview', label: 'ScrollView' },
	{ key: 'gradient', label: 'Gradient (ink-gradient port)' },
]
//#endregion Menu

//#region App
export function App() {
	const [activeDemo, setActiveDemo] = useState<DemoName | null>(null)

	if (activeDemo === 'timer')
		return <TimerDemo onBack={() => setActiveDemo(null)} />
	if (activeDemo === 'treeview')
		return <TreeViewDemo onBack={() => setActiveDemo(null)} />
	if (activeDemo === 'combobox')
		return <ComboboxDemo onBack={() => setActiveDemo(null)} />
	if (activeDemo === 'jsonviewer')
		return <JsonViewerDemo onBack={() => setActiveDemo(null)} />
	if (activeDemo === 'filepicker')
		return <FilePickerDemo onBack={() => setActiveDemo(null)} />
	if (activeDemo === 'scrollview')
		return <ScrollViewDemo onBack={() => setActiveDemo(null)} />
	if (activeDemo === 'gradient')
		return <GradientDemo onBack={() => setActiveDemo(null)} />

	return <Menu onSelect={setActiveDemo} />
}

function Menu({ onSelect }: { onSelect: (demo: DemoName) => void }) {
	const [focused, setFocused] = useState(0)

	useInput((_input, key) => {
		if (key.downArrow) setFocused((f) => Math.min(f + 1, DEMOS.length - 1))
		if (key.upArrow) setFocused((f) => Math.max(f - 1, 0))
		if (key.return) onSelect(DEMOS[focused]!.key)
	})

	return (
		<Box style={{ flexDirection: 'column', padding: 1 }}>
			<Text style={{ fontWeight: 'bold', color: 'cyan' }}>
				wolf-tui Community Components Showcase
			</Text>
			<Text style={{ dimColor: true }}>
				Use ↑↓ to navigate, Enter to select, Ctrl+C to exit
			</Text>
			<Box style={{ flexDirection: 'column', marginTop: 1 }}>
				{DEMOS.map((demo, i) => (
					<Text
						key={demo.key}
						style={{ color: i === focused ? 'blue' : undefined }}
					>
						{i === focused ? '❯ ' : '  '}
						{demo.label}
					</Text>
				))}
			</Box>
		</Box>
	)
}
//#endregion App

//#region Entry
if (typeof process !== 'undefined' && !process.env.WOLFIE_VERIFY) {
	render(<App />)
}
//#endregion Entry

// examples/solid_showcase/src/index.tsx
import { createSignal, Show, For } from 'solid-js'
import { render, Box, Text, useInput } from '@wolf-tui/solid'
import { TimerDemo } from './demos/TimerDemo'
import { TreeViewDemo } from './demos/TreeViewDemo'
import { ComboboxDemo } from './demos/ComboboxDemo'
import { JsonViewerDemo } from './demos/JsonViewerDemo'
import { FilePickerDemo } from './demos/FilePickerDemo'
import { ScrollViewDemo } from './demos/ScrollViewDemo'
import { GradientDemo } from './demos/GradientDemo'

//#region Menu
type DemoName =
	| 'timer'
	| 'treeview'
	| 'combobox'
	| 'jsonviewer'
	| 'filepicker'
	| 'scrollview'
	| 'gradient'

const DEMOS: Array<{ key: DemoName; label: string }> = [
	{ key: 'timer', label: 'Timer / Countdown / Stopwatch' },
	{ key: 'treeview', label: 'TreeView' },
	{ key: 'combobox', label: 'Combobox (Autocomplete)' },
	{ key: 'jsonviewer', label: 'JsonViewer' },
	{ key: 'filepicker', label: 'FilePicker' },
	{ key: 'scrollview', label: 'ScrollView' },
	{ key: 'gradient', label: 'Gradient (ink-gradient port)' },
]
//#endregion Menu

//#region App
export function App() {
	const [activeDemo, setActiveDemo] = createSignal<DemoName | null>(null)
	const goBack = () => setActiveDemo(null)

	return (
		<>
			<Show when={activeDemo() === 'timer'}>
				<TimerDemo onBack={goBack} />
			</Show>
			<Show when={activeDemo() === 'treeview'}>
				<TreeViewDemo onBack={goBack} />
			</Show>
			<Show when={activeDemo() === 'combobox'}>
				<ComboboxDemo onBack={goBack} />
			</Show>
			<Show when={activeDemo() === 'jsonviewer'}>
				<JsonViewerDemo onBack={goBack} />
			</Show>
			<Show when={activeDemo() === 'filepicker'}>
				<FilePickerDemo onBack={goBack} />
			</Show>
			<Show when={activeDemo() === 'scrollview'}>
				<ScrollViewDemo onBack={goBack} />
			</Show>
			<Show when={activeDemo() === 'gradient'}>
				<GradientDemo onBack={goBack} />
			</Show>
			<Show when={activeDemo() === null}>
				<Menu onSelect={setActiveDemo} />
			</Show>
		</>
	)
}

function Menu(props: { onSelect: (demo: DemoName) => void }) {
	const [focused, setFocused] = createSignal(0)

	useInput((_input, key) => {
		if (key.downArrow) setFocused((f) => Math.min(f + 1, DEMOS.length - 1))
		if (key.upArrow) setFocused((f) => Math.max(f - 1, 0))
		if (key.return) props.onSelect(DEMOS[focused()]!.key)
	})

	return (
		<Box style={{ flexDirection: 'column', padding: 1 }}>
			<Text style={{ fontWeight: 'bold', color: 'cyan' }}>
				wolf-tui Community Components Showcase
			</Text>
			<Text style={{ dimColor: true }}>
				Use arrow-keys to navigate, Enter to select, Ctrl+C to exit
			</Text>
			<Box style={{ flexDirection: 'column', marginTop: 1 }}>
				<For each={DEMOS}>
					{(demo, i) => (
						<Text style={{ color: i() === focused() ? 'blue' : undefined }}>
							{i() === focused() ? '> ' : '  '}
							{demo.label}
						</Text>
					)}
				</For>
			</Box>
		</Box>
	)
}
//#endregion App

//#region Entry
if (typeof process !== 'undefined' && process.env['WOLFIE_VERIFY'] !== '1') {
	render(App, {
		maxFps: 30,
	})
}
//#endregion Entry
