// examples/solid_showcase/src/demos/BigTextDemo.tsx
import { createSignal, Match, Switch } from 'solid-js'
import { Box, Text, useInput, BigText, type BigTextFont } from '@wolf-tui/solid'

//#region Data
const FONTS: readonly BigTextFont[] = [
	'block',
	'slick',
	'tiny',
	'grid',
	'pallet',
	'shade',
	'simple',
	'simpleBlock',
	'3d',
	'simple3d',
	'chrome',
	'huge',
]

// Digit keys mapped 1..9, then 0, -, = for the remaining 3 fonts (12 total).
const FONT_KEYS = [
	'1',
	'2',
	'3',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'0',
	'-',
	'=',
] as const

type ColorMode = 'solo' | 'gradient' | 'default'
const COLOR_MODES: readonly ColorMode[] = ['solo', 'gradient', 'default']
//#endregion Data

//#region Component
export function BigTextDemo(props: { onBack: () => void }) {
	const [fontIndex, setFontIndex] = createSignal(0)
	const [colorModeIndex, setColorModeIndex] = createSignal(0)

	const currentFont = () => FONTS[fontIndex()]!
	const currentColorMode = () => COLOR_MODES[colorModeIndex()]!

	useInput((input, key) => {
		if (key.escape) {
			props.onBack()
			return
		}
		if (input === 'c' || input === 'C') {
			setColorModeIndex((i) => (i + 1) % COLOR_MODES.length)
			return
		}
		const idx = FONT_KEYS.indexOf(input as (typeof FONT_KEYS)[number])
		if (idx !== -1 && idx < FONTS.length) {
			setFontIndex(idx)
		}
	})

	return (
		<Box style={{ flexDirection: 'column', padding: 1 }}>
			<Text style={{ fontWeight: 'bold', color: 'cyan' }}>BigText Demo</Text>
			<Text style={{ dimColor: true }}>
				BigText Demo — 1-9/0/-/= switch font, C cycle color mode, Esc back
			</Text>
			<Text style={{ marginTop: 1 }}>
				Font: <Text style={{ color: 'yellow' }}>{currentFont()}</Text>
			</Text>
			<Text>
				Color mode:{' '}
				<Text style={{ color: 'magenta' }}>{currentColorMode()}</Text>
			</Text>
			<Box style={{ marginTop: 1 }}>
				<Switch>
					<Match when={currentColorMode() === 'solo'}>
						<BigText
							text="WOLF"
							font={currentFont()}
							colors={['cyan']}
							space={false}
							align="center"
						/>
					</Match>
					<Match when={currentColorMode() === 'gradient'}>
						<BigText
							text="WOLF"
							font={currentFont()}
							gradient={['red', 'blue']}
							space={false}
							align="center"
						/>
					</Match>
					<Match when={currentColorMode() === 'default'}>
						<BigText
							text="WOLF"
							font={currentFont()}
							space={false}
							align="center"
						/>
					</Match>
				</Switch>
			</Box>
		</Box>
	)
}
//#endregion Component

// examples/svelte_showcase/src/demos/BigTextDemo.svelte
<!-- #region Script -->
<script lang="ts">
	import {
		Box,
		Text,
		useInput,
		BigText,
		type BigTextFont,
		type BigTextGradient,
	} from '@wolf-tui/svelte'

	let { onBack }: { onBack: () => void } = $props()

	//#region Menu Data
	const FONTS: readonly BigTextFont[] = [
		'block',
		'slick',
		'tiny',
		'grid',
		'pallet',
		'shade',
		'simple',
		'simpleBlock',
		'3d',
		'simple3d',
		'chrome',
		'huge',
	]

	// Keys 1-9 → fonts 0-8, then 0, -, = → fonts 9-11.
	// WHY: digits only go up to 9, so we need non-digit keys for the last three
	// font slots. The trio 0, -, = sits next to 9 on a standard keyboard row.
	const FONT_KEYS: readonly string[] = [
		'1',
		'2',
		'3',
		'4',
		'5',
		'6',
		'7',
		'8',
		'9',
		'0',
		'-',
		'=',
	]

	type ColorMode = 'solo' | 'gradient' | 'default'
	const COLOR_MODES: readonly ColorMode[] = ['solo', 'gradient', 'default']
	//#endregion Menu Data

	//#region State
	let fontIndex = $state(0)
	let colorModeIndex = $state(0)

	let currentFont = $derived(FONTS[fontIndex] ?? 'block')
	let colorMode = $derived<ColorMode>(COLOR_MODES[colorModeIndex] ?? 'solo')

	// Solo: single cycling color. Gradient: two-stop magenta→cyan sweep.
	// Default: cfonts' own built-in per-font colors.
	let soloColors = $derived<readonly string[] | undefined>(
		colorMode === 'solo' ? ['cyan'] : undefined
	)
	let gradientSpec = $derived<BigTextGradient | undefined>(
		colorMode === 'gradient' ? ['magenta', 'cyan'] : undefined
	)
	//#endregion State

	//#region Input
	useInput((input, key) => {
		if (key.escape) {
			onBack()
			return
		}
		if (input === 'c' || input === 'C') {
			colorModeIndex = (colorModeIndex + 1) % COLOR_MODES.length
			return
		}
		const idx = FONT_KEYS.indexOf(input)
		if (idx !== -1 && idx < FONTS.length) {
			fontIndex = idx
		}
	})
	//#endregion Input
</script>
<!-- #endregion Script -->

<!-- #region Template -->
<Box style={{ flexDirection: 'column', padding: 1 }}>
	<Text style={{ fontWeight: 'bold', color: 'cyan' }}>BigText Demo</Text>
	<Text style={{ dimColor: true }}>
		BigText Demo — 1-9/0/-/= switch font, C cycle color mode, Esc back
	</Text>
	<Box style={{ marginTop: 1, flexDirection: 'column' }}>
		<Text>Font: <Text style={{ color: 'yellow' }}>{currentFont}</Text></Text>
		<Text>Color mode: <Text style={{ color: 'yellow' }}>{colorMode}</Text></Text>
	</Box>
	<Box style={{ marginTop: 1 }}>
		<BigText
			text="WOLF"
			font={currentFont}
			colors={soloColors}
			gradient={gradientSpec}
			space={false}
			align="center"
		/>
	</Box>
</Box>
<!-- #endregion Template -->
