// examples/react_showcase/src/demos/ScrollViewDemo.tsx
import { useState } from 'react'
import { Box, Text, useInput, ScrollView } from '@wolf-tui/react'

//#region Data
const ITEMS = Array.from({ length: 30 }, (_, i) => ({
	id: `item-${i}`,
	label: `Item ${String(i + 1).padStart(2, '0')}`,
}))
//#endregion Data

//#region Component
export function ScrollViewDemo({ onBack }: { onBack: () => void }) {
	const [offset, setOffset] = useState(0)
	const [contentHeight, setContentHeight] = useState(0)
	const viewportHeight = 8

	useInput((_input, key) => {
		if (key.escape) onBack()
	})

	return (
		<Box style={{ flexDirection: 'column', padding: 1 }}>
			<Text style={{ fontWeight: 'bold', color: 'cyan' }}>ScrollView Demo</Text>
			<Text style={{ dimColor: true }}>
				↑↓=scroll PgUp/PgDn=page Home/End=edges Esc=back
			</Text>
			<Box
				style={{
					marginTop: 1,
					borderStyle: 'round',
					borderColor: 'gray',
					flexDirection: 'column',
				}}
			>
				<ScrollView
					height={viewportHeight}
					offset={offset}
					onScroll={setOffset}
					onContentHeightChange={setContentHeight}
				>
					{ITEMS.map((item) => (
						<Text key={item.id}>{item.label}</Text>
					))}
				</ScrollView>
			</Box>
			<Text style={{ dimColor: true, marginTop: 1 }}>
				offset={offset} contentHeight={contentHeight} viewport={viewportHeight}
			</Text>
		</Box>
	)
}
//#endregion Component

// examples/svelte_showcase/src/demos/ScrollViewDemo.svelte
<!-- #region Script -->
<script lang="ts">
	import { Box, Text, ScrollView, useInput } from '@wolf-tui/svelte'

	let { onBack }: { onBack: () => void } = $props()

	//#region State
	let offset = $state(0)
	let contentHeight = $state(0)
	const viewportHeight = 8
	const items = Array.from(
		{ length: 30 },
		(_, i) => `Item ${String(i + 1).padStart(2, '0')}`
	)
	//#endregion State

	useInput((_input, key) => {
		if (key.escape) onBack()
	})
</script>
<!-- #endregion Script -->

<!-- #region Template -->
<Box style={{ flexDirection: 'column', padding: 1 }}>
	<Text style={{ fontWeight: 'bold', color: 'cyan' }}>ScrollView Demo</Text>
	<Text style={{ dimColor: true }}>
		↑↓=scroll PgUp/PgDn=page Home/End=edges Esc=back
	</Text>

	<Box
		style={{
			flexDirection: 'column',
			marginTop: 1,
			borderStyle: 'round',
			borderColor: 'gray',
		}}
	>
		<ScrollView
			height={viewportHeight}
			onScroll={(o) => {
				offset = o
			}}
			onContentHeightChange={(h) => {
				contentHeight = h
			}}
		>
			<Box style={{ flexDirection: 'column' }}>
				{#each items as item (item)}
					<Text>{item}</Text>
				{/each}
			</Box>
		</ScrollView>
	</Box>

	<Text style={{ dimColor: true, marginTop: 1 }}>
		offset={offset} contentHeight={contentHeight} viewport={viewportHeight}
	</Text>
</Box>
<!-- #endregion Template -->
