// examples/vue_showcase/src/demos/ScrollViewDemo.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Box, Text, useInput, ScrollView } from '@wolf-tui/vue'

const props = defineProps<{ onBack: () => void }>()

useInput((_input, key) => {
	if (key.escape) props.onBack()
})

//#region State
const offset = ref(0)
const contentHeight = ref(0)

const VIEWPORT_HEIGHT = 8
const TOTAL_ITEMS = 30

const items = computed(() =>
	Array.from(
		{ length: TOTAL_ITEMS },
		(_, i) => `Item ${String(i + 1).padStart(2, '0')}`
	)
)

function handleScroll(value: number) {
	offset.value = value
}

function handleContentHeightChange(height: number) {
	contentHeight.value = height
}
//#endregion State
</script>

<script lang="ts">
export default { name: 'ScrollViewDemo' }
</script>

<template>
	<Box :style="{ flexDirection: 'column', padding: 1 }">
		<Text :style="{ fontWeight: 'bold', color: 'cyan' }">ScrollView Demo</Text>
		<Text :style="{ dimColor: true }">
			↑↓=scroll PgUp/PgDn=page Home/End=edges Esc=back
		</Text>
		<Box :style="{ marginTop: 1, borderStyle: 'round', borderColor: 'gray' }">
			<ScrollView
				:height="VIEWPORT_HEIGHT"
				:offset="offset"
				:on-scroll="handleScroll"
				:on-content-height-change="handleContentHeightChange"
			>
				<Text v-for="item in items" :key="item">{{ item }}</Text>
			</ScrollView>
		</Box>
		<Text :style="{ dimColor: true, marginTop: 1 }">
			offset={{ offset }} contentHeight={{ contentHeight }} viewport={{
				VIEWPORT_HEIGHT
			}}
		</Text>
	</Box>
</template>

// examples/svelte_showcase/src/demos/ScrollViewDemo.svelte
<!-- #region Script -->
<script lang="ts">
	import { Box, Text, ScrollView, useInput } from '@wolf-tui/svelte'

	let { onBack }: { onBack: () => void } = $props()

	//#region State
	let offset = $state(0)
	let contentHeight = $state(0)
	const viewportHeight = 8
	const items = Array.from(
		{ length: 30 },
		(_, i) => `Item ${String(i + 1).padStart(2, '0')}`
	)
	//#endregion State

	useInput((_input, key) => {
		if (key.escape) onBack()
	})
</script>
<!-- #endregion Script -->

<!-- #region Template -->
<Box style={{ flexDirection: 'column', padding: 1 }}>
	<Text style={{ fontWeight: 'bold', color: 'cyan' }}>ScrollView Demo</Text>
	<Text style={{ dimColor: true }}>
		↑↓=scroll PgUp/PgDn=page Home/End=edges Esc=back
	</Text>

	<Box
		style={{
			flexDirection: 'column',
			marginTop: 1,
			borderStyle: 'round',
			borderColor: 'gray',
		}}
	>
		<ScrollView
			height={viewportHeight}
			onScroll={(o) => {
				offset = o
			}}
			onContentHeightChange={(h) => {
				contentHeight = h
			}}
		>
			<Box style={{ flexDirection: 'column' }}>
				{#each items as item (item)}
					<Text>{item}</Text>
				{/each}
			</Box>
		</ScrollView>
	</Box>

	<Text style={{ dimColor: true, marginTop: 1 }}>
		offset={offset} contentHeight={contentHeight} viewport={viewportHeight}
	</Text>
</Box>
<!-- #endregion Template -->
