// packages/solid/src/composables/use-file-picker-state.ts
import { basename } from 'node:path'
import { createSignal, createMemo, createEffect, on, onMount } from 'solid-js'
import {
	filePickerReducer,
	createDefaultFilePickerState,
	readDirectory,
	formatFileSize,
	type FilePickerState,
	type FilePickerAction,
	type FileTypeFilter,
	type FilePickerMode,
} from '@wolf-tui/shared'
import type { FilePickerVisibleEntry } from '@wolf-tui/shared'

//#region Types
export type UseFilePickerStateProps = {
	/**
	 * Initial directory path.
	 *
	 * @default '.'
	 */
	initialPath?: string

	/**
	 * Allow selecting multiple files.
	 *
	 * @default false
	 */
	multiSelect?: boolean

	/**
	 * Filter by file type.
	 *
	 * @default 'all'
	 */
	fileTypes?: FileTypeFilter

	/**
	 * Show hidden files (dotfiles).
	 *
	 * @default false
	 */
	showHidden?: boolean

	/**
	 * Show file size details.
	 *
	 * @default false
	 */
	showDetails?: boolean

	/**
	 * Maximum visible entries.
	 *
	 * @default 10
	 */
	maxHeight?: number

	/**
	 * Called when file selection is confirmed.
	 */
	onSelect?: (paths: string[]) => void

	/**
	 * Called on every selection toggle (Space key). Fires in real-time
	 * as the user toggles items, unlike onSelect which fires on confirmation.
	 */
	onSelectionChange?: (paths: string[]) => void

	/**
	 * Called when the current directory changes.
	 */
	onDirectoryChange?: (path: string) => void
}

export type FilePickerStateResult = {
	currentPath: () => string
	visibleEntries: () => FilePickerVisibleEntry[]
	mode: () => FilePickerMode
	filterText: () => string
	multiSelect: () => boolean
	showDetails: () => boolean
	selectedPaths: () => ReadonlySet<string>
	errorMessage: () => string | undefined
	hasScrollUp: () => boolean
	hasScrollDown: () => boolean
	scrollUpCount: () => number
	scrollDownCount: () => number
	dispatch: (action: FilePickerAction) => void
	loadDirectory: (path: string) => void
}
//#endregion Types

//#region Composable
export const useFilePickerState = ({
	initialPath = '.',
	multiSelect = false,
	fileTypes = 'all',
	showHidden = false,
	showDetails = false,
	maxHeight = 10,
	onSelect,
	onSelectionChange,
	onDirectoryChange,
}: UseFilePickerStateProps): FilePickerStateResult => {
	const initialState = createDefaultFilePickerState({
		initialPath,
		multiSelect,
		fileTypes,
		showHidden,
		showDetails,
		maxHeight,
	})

	const [state, setState] = createSignal<FilePickerState>(initialState)

	const dispatch = (action: FilePickerAction) => {
		setState((prev) => filePickerReducer(prev, action))
	}

	const loadDirectory = (path: string) => {
		dispatch({ type: 'set-loading' })

		readDirectory(path, { showHidden })
			.then((entries) => {
				dispatch({ type: 'set-entries', path, entries })
			})
			.catch((err: unknown) => {
				const message = err instanceof Error ? err.message : String(err)
				dispatch({ type: 'set-error', error: message })
			})
	}

	// Load initial directory on mount
	onMount(() => {
		loadDirectory(initialPath)
	})

	// Watch for path changes to trigger directory loading
	createEffect(
		on(
			() => state().currentPath,
			(newPath, oldPath) => {
				if (newPath !== oldPath && state().mode === 'loading') {
					loadDirectory(newPath)
					onDirectoryChange?.(newPath)
				}
			},
			{ defer: true }
		)
	)

	// Watch previousSelectedPaths for onSelect callback -- fires on confirmation, not every toggle
	createEffect(
		on(
			() => state().previousSelectedPaths,
			(_current, _prev) => {
				const paths = state().selectedPaths
				if (_current !== _prev && paths.size > 0) {
					onSelect?.([...paths])
				}
			},
			{ defer: true }
		)
	)

	// onSelectionChange — fires on every toggle (Space), not just confirmation
	createEffect(
		on(
			() => state().selectedPaths,
			(current, previous) => {
				if (current !== previous) {
					onSelectionChange?.([...current])
				}
			},
			{ defer: true }
		)
	)

	const currentPath = createMemo(() => state().currentPath)
	const mode = createMemo(() => state().mode)
	const filterText = createMemo(() => state().filterText)
	const multiSelectSignal = createMemo(() => state().multiSelect)
	const showDetailsSignal = createMemo(() => state().showDetails)
	const selectedPaths = createMemo(() => state().selectedPaths)
	const errorMessage = createMemo(() => state().errorMessage)

	const visibleEntries = createMemo((): FilePickerVisibleEntry[] => {
		const s = state()
		const entries = s.mode === 'filtering' ? s.filteredEntries : s.entries
		const {
			viewportFrom,
			viewportTo,
			focusedIndex,
			selectedPaths: selected,
		} = s

		const visible: FilePickerVisibleEntry[] = []
		for (let i = viewportFrom; i < viewportTo && i < entries.length; i++) {
			const entry = entries[i]!
			const symlinkBasename = entry.symlinkTarget
				? basename(entry.symlinkTarget)
				: undefined
			const displayName =
				entry.kind === 'directory'
					? `${entry.name}/`
					: entry.kind === 'symlink' && symlinkBasename
						? `${entry.name} -> ${symlinkBasename}`
						: entry.name

			visible.push({
				name: entry.name,
				displayName,
				path: entry.path,
				kind: entry.kind,
				symlinkTargetKind: entry.symlinkTargetKind,
				symlinkTargetBasename: symlinkBasename,
				size: formatFileSize(entry.size),
				isSelected: selected.has(entry.path),
				isFocused: i === focusedIndex,
			})
		}

		return visible
	})

	const hasScrollUp = createMemo(() => state().viewportFrom > 0)
	const hasScrollDown = createMemo(() => {
		const s = state()
		const entries = s.mode === 'filtering' ? s.filteredEntries : s.entries
		return s.viewportTo < entries.length
	})
	const scrollUpCount = createMemo(() => state().viewportFrom)
	const scrollDownCount = createMemo(() => {
		const s = state()
		const entries = s.mode === 'filtering' ? s.filteredEntries : s.entries
		return Math.max(0, entries.length - s.viewportTo)
	})

	return {
		currentPath,
		visibleEntries,
		mode,
		filterText,
		multiSelect: multiSelectSignal,
		showDetails: showDetailsSignal,
		selectedPaths,
		errorMessage,
		hasScrollUp,
		hasScrollDown,
		scrollUpCount,
		scrollDownCount,
		dispatch,
		loadDirectory,
	}
}
//#endregion Composable

// packages/react/src/components/FilePicker/use-file-picker-state.ts
import { useReducer, useCallback, useMemo, useEffect, useRef } from 'react'
import {
	filePickerReducer,
	createDefaultFilePickerState,
	readDirectory,
	type FilePickerState,
	type FileTypeFilter,
	type IFileEntry,
} from '@wolf-tui/shared'

//#region Types
export type IUseFilePickerStateProps = {
	/**
	 * Initial directory path.
	 *
	 * @default '.'
	 */
	initialPath?: string

	/**
	 * String filter or predicate function for entries.
	 */
	filter?: string | ((entry: IFileEntry) => boolean)

	/**
	 * Show hidden files (dotfiles).
	 *
	 * @default false
	 */
	showHidden?: boolean

	/**
	 * Show file details (size column).
	 *
	 * @default false
	 */
	showDetails?: boolean

	/**
	 * Enable multi-selection.
	 *
	 * @default false
	 */
	multiSelect?: boolean

	/**
	 * Filter by entry kind: 'files', 'directories', or 'all'.
	 *
	 * @default 'all'
	 */
	fileTypes?: FileTypeFilter

	/**
	 * Maximum visible entries.
	 *
	 * @default 10
	 */
	maxHeight?: number

	/**
	 * Callback when selection is confirmed (Enter key).
	 */
	onSelect?: (paths: string[]) => void

	/**
	 * Callback on every selection toggle (Space key). Fires in real-time
	 * as the user toggles items, unlike onSelect which fires on confirmation.
	 */
	onSelectionChange?: (paths: string[]) => void

	/**
	 * Callback on cancel (Escape).
	 */
	onCancel?: () => void

	/**
	 * Callback when current directory changes.
	 */
	onDirectoryChange?: (path: string) => void
}

export type IFilePickerState = {
	currentPath: string
	entries: IFileEntry[]
	focusedIndex: number
	selectedPaths: ReadonlySet<string>
	multiSelect: boolean
	showDetails: boolean
	mode: FilePickerState['mode']
	filterText: string
	viewportFrom: number
	viewportTo: number
	errorMessage: string | undefined
	activeEntries: ReadonlyArray<IFileEntry>
	visibleEntries: IFileEntry[]

	focusNext: () => void
	focusPrevious: () => void
	focusFirst: () => void
	focusLast: () => void
	select: () => void
	toggleSelect: () => void
	goParent: () => void
	enterDirectory: () => void
	enterFilterMode: () => void
	exitFilterMode: () => void
	filterInsert: (text: string) => void
	filterDelete: () => void
}
//#endregion Types

//#region Hook
export function useFilePickerState({
	initialPath = '.',
	filter,
	showHidden = false,
	showDetails = false,
	multiSelect = false,
	fileTypes = 'all',
	maxHeight = 10,
	onSelect,
	onSelectionChange,
	onCancel: _onCancel,
	onDirectoryChange,
}: IUseFilePickerStateProps): IFilePickerState {
	const [state, dispatch] = useReducer(
		filePickerReducer,
		{ initialPath, multiSelect, fileTypes, showHidden, showDetails, maxHeight },
		createDefaultFilePickerState
	)

	const prevPathRef = useRef(state.currentPath)
	const prevSelectedRef = useRef(state.previousSelectedPaths)
	const filterRef = useRef(filter)
	filterRef.current = filter

	// Load directory on mount and when currentPath changes
	useEffect(() => {
		let cancelled = false
		const currentFilter = filterRef.current

		dispatch({ type: 'set-loading' })
		readDirectory(state.currentPath, { showHidden })
			.then((entries) => {
				if (cancelled) return

				let filtered = entries
				if (currentFilter) {
					if (typeof currentFilter === 'string') {
						const lower = currentFilter.toLowerCase()
						filtered = entries.filter((e) =>
							e.name.toLowerCase().includes(lower)
						)
					} else {
						filtered = entries.filter(currentFilter)
					}
				}

				if (fileTypes === 'files') {
					filtered = filtered.filter((e) => e.kind !== 'directory')
				} else if (fileTypes === 'directories') {
					filtered = filtered.filter(
						(e) => e.kind === 'directory' || e.kind === 'symlink'
					)
				}

				dispatch({
					type: 'set-entries',
					path: state.currentPath,
					entries: filtered,
				})
			})
			.catch((err: unknown) => {
				if (cancelled) return
				const message = err instanceof Error ? err.message : String(err)
				dispatch({ type: 'set-error', error: message })
			})

		return () => {
			cancelled = true
		}
	}, [state.currentPath, showHidden, fileTypes])

	// onDirectoryChange callback
	useEffect(() => {
		if (state.currentPath !== prevPathRef.current) {
			prevPathRef.current = state.currentPath
			onDirectoryChange?.(state.currentPath)
		}
	}, [state.currentPath, onDirectoryChange])

	// onSelectionChange callback — fires on every toggle (Space)
	const prevToggleRef = useRef(state.selectedPaths)
	useEffect(() => {
		if (state.selectedPaths !== prevToggleRef.current) {
			prevToggleRef.current = state.selectedPaths
			onSelectionChange?.([...state.selectedPaths])
		}
	}, [state.selectedPaths, onSelectionChange])

	// onSelect callback — fires only on confirmation (Enter), not on every toggle
	// The shared reducer sets previousSelectedPaths on confirm actions
	useEffect(() => {
		if (
			state.previousSelectedPaths !== prevSelectedRef.current &&
			state.selectedPaths.size > 0
		) {
			prevSelectedRef.current = state.previousSelectedPaths
			onSelect?.([...state.selectedPaths])
		}
	}, [state.previousSelectedPaths, state.selectedPaths, onSelect])

	const focusNext = useCallback(() => {
		dispatch({ type: 'focus-next' })
	}, [])

	const focusPrevious = useCallback(() => {
		dispatch({ type: 'focus-previous' })
	}, [])

	const focusFirst = useCallback(() => {
		dispatch({ type: 'focus-first' })
	}, [])

	const focusLast = useCallback(() => {
		dispatch({ type: 'focus-last' })
	}, [])

	const select = useCallback(() => {
		dispatch({ type: 'select' })
	}, [])

	const toggleSelect = useCallback(() => {
		dispatch({ type: 'toggle-select' })
	}, [])

	const goParent = useCallback(() => {
		dispatch({ type: 'go-parent' })
	}, [])

	const enterDirectory = useCallback(() => {
		dispatch({ type: 'enter-directory' })
	}, [])

	const enterFilterMode = useCallback(() => {
		dispatch({ type: 'enter-filter-mode' })
	}, [])

	const exitFilterMode = useCallback(() => {
		dispatch({ type: 'exit-filter-mode' })
	}, [])

	const filterInsert = useCallback((text: string) => {
		dispatch({ type: 'filter-insert', text })
	}, [])

	const filterDelete = useCallback(() => {
		dispatch({ type: 'filter-delete' })
	}, [])

	const activeEntries = useMemo(() => {
		return state.mode === 'filtering' ? state.filteredEntries : state.entries
	}, [state.mode, state.filteredEntries, state.entries])

	const visibleEntries = useMemo(() => {
		return activeEntries.slice(state.viewportFrom, state.viewportTo)
	}, [activeEntries, state.viewportFrom, state.viewportTo])

	return {
		currentPath: state.currentPath,
		entries: state.entries,
		focusedIndex: state.focusedIndex,
		selectedPaths: state.selectedPaths,
		multiSelect: state.multiSelect,
		showDetails: state.showDetails,
		mode: state.mode,
		filterText: state.filterText,
		viewportFrom: state.viewportFrom,
		viewportTo: state.viewportTo,
		errorMessage: state.errorMessage,
		activeEntries,
		visibleEntries,
		focusNext,
		focusPrevious,
		focusFirst,
		focusLast,
		select,
		toggleSelect,
		goParent,
		enterDirectory,
		enterFilterMode,
		exitFilterMode,
		filterInsert,
		filterDelete,
	}
}
//#endregion Hook
