// examples/solid_showcase/src/demos/BigTextDemo.tsx
import { createSignal, Match, Switch } from 'solid-js'
import { Box, Text, useInput, BigText, type BigTextFont } from '@wolf-tui/solid'

//#region Data
const FONTS: readonly BigTextFont[] = [
	'block',
	'slick',
	'tiny',
	'grid',
	'pallet',
	'shade',
	'simple',
	'simpleBlock',
	'3d',
	'simple3d',
	'chrome',
	'huge',
]

// Digit keys mapped 1..9, then 0, -, = for the remaining 3 fonts (12 total).
const FONT_KEYS = [
	'1',
	'2',
	'3',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'0',
	'-',
	'=',
] as const

type ColorMode = 'solo' | 'gradient' | 'default'
const COLOR_MODES: readonly ColorMode[] = ['solo', 'gradient', 'default']
//#endregion Data

//#region Component
export function BigTextDemo(props: { onBack: () => void }) {
	const [fontIndex, setFontIndex] = createSignal(0)
	const [colorModeIndex, setColorModeIndex] = createSignal(0)

	const currentFont = () => FONTS[fontIndex()]!
	const currentColorMode = () => COLOR_MODES[colorModeIndex()]!

	useInput((input, key) => {
		if (key.escape) {
			props.onBack()
			return
		}
		if (input === 'c' || input === 'C') {
			setColorModeIndex((i) => (i + 1) % COLOR_MODES.length)
			return
		}
		const idx = FONT_KEYS.indexOf(input as (typeof FONT_KEYS)[number])
		if (idx !== -1 && idx < FONTS.length) {
			setFontIndex(idx)
		}
	})

	return (
		<Box style={{ flexDirection: 'column', padding: 1 }}>
			<Text style={{ fontWeight: 'bold', color: 'cyan' }}>BigText Demo</Text>
			<Text style={{ dimColor: true }}>
				BigText Demo — 1-9/0/-/= switch font, C cycle color mode, Esc back
			</Text>
			<Text style={{ marginTop: 1 }}>
				Font: <Text style={{ color: 'yellow' }}>{currentFont()}</Text>
			</Text>
			<Text>
				Color mode:{' '}
				<Text style={{ color: 'magenta' }}>{currentColorMode()}</Text>
			</Text>
			<Box style={{ marginTop: 1 }}>
				<Switch>
					<Match when={currentColorMode() === 'solo'}>
						<BigText
							text="WOLF"
							font={currentFont()}
							colors={['cyan']}
							space={false}
							align="center"
						/>
					</Match>
					<Match when={currentColorMode() === 'gradient'}>
						<BigText
							text="WOLF"
							font={currentFont()}
							gradient={['red', 'blue']}
							space={false}
							align="center"
						/>
					</Match>
					<Match when={currentColorMode() === 'default'}>
						<BigText
							text="WOLF"
							font={currentFont()}
							space={false}
							align="center"
						/>
					</Match>
				</Switch>
			</Box>
		</Box>
	)
}
//#endregion Component

// examples/vue_showcase/src/demos/BigTextDemo.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Box, Text, useInput, BigText, type BigTextFont } from '@wolf-tui/vue'

const props = defineProps<{ onBack: () => void }>()

//#region State
const FONTS: readonly BigTextFont[] = [
	'block',
	'slick',
	'tiny',
	'grid',
	'pallet',
	'shade',
	'simple',
	'simpleBlock',
	'3d',
	'simple3d',
	'chrome',
	'huge',
] as const

const FONT_KEYS: readonly string[] = [
	'1',
	'2',
	'3',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'0',
	'-',
	'=',
]

type ColorMode = 'solo' | 'gradient' | 'default'
const COLOR_MODES: readonly ColorMode[] = [
	'solo',
	'gradient',
	'default',
] as const

const fontIndex = ref(0)
const colorModeIndex = ref(0)

const currentFont = computed<BigTextFont>(() => FONTS[fontIndex.value]!)
const currentColorMode = computed<ColorMode>(
	() => COLOR_MODES[colorModeIndex.value]!
)

const soloColors = computed<readonly string[]>(() => ['cyan'])
const gradientColors = computed<readonly string[]>(() => ['red', 'blue'])
//#endregion State

//#region Input
useInput((input, key) => {
	if (key.escape) {
		props.onBack()
		return
	}
	const idx = FONT_KEYS.indexOf(input)
	if (idx !== -1) {
		fontIndex.value = idx
		return
	}
	if (input === 'c' || input === 'C') {
		colorModeIndex.value = (colorModeIndex.value + 1) % COLOR_MODES.length
	}
})
//#endregion Input
</script>

<script lang="ts">
export default { name: 'BigTextDemo' }
</script>

<template>
	<Box :style="{ flexDirection: 'column', padding: 1 }">
		<Text :style="{ fontWeight: 'bold', color: 'cyan' }">BigText Demo</Text>
		<Text :style="{ dimColor: true }">
			BigText Demo — 1-9/0/-/= switch font, C cycle color mode, Esc back
		</Text>
		<Text :style="{ marginTop: 1 }">Font: {{ currentFont }}</Text>
		<Text :style="{ dimColor: true }">Color mode: {{ currentColorMode }}</Text>
		<Box :style="{ marginTop: 1 }">
			<BigText
				v-if="currentColorMode === 'solo'"
				text="WOLF"
				:font="currentFont"
				:colors="soloColors"
				:space="false"
				align="center"
			/>
			<BigText
				v-else-if="currentColorMode === 'gradient'"
				text="WOLF"
				:font="currentFont"
				:gradient="gradientColors"
				:space="false"
				align="center"
			/>
			<BigText
				v-else
				text="WOLF"
				:font="currentFont"
				:space="false"
				align="center"
			/>
		</Box>
	</Box>
</template>
