// packages/vue/src/components/Timer.tsx
import {
	defineComponent,
	toRef,
	type PropType,
	type DefineComponent,
} from 'vue'
import {
	renderTimer,
	defaultTimerTheme,
	type TimerRenderTheme,
	type TimerVariant,
	type TimeFormat,
	type ILap,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { useTimerState } from '../composables/use-timer-state'
import { useTimer } from '../composables/use-timer'
import { wNodeToVue } from '../wnode/wnode-to-vue'

//#region Types
export interface TimerProps {
	/**
	 * Timer variant: 'timer' | 'countdown' | 'stopwatch'.
	 *
	 * @default 'timer'
	 */
	variant?: TimerVariant

	/**
	 * Start automatically on mount.
	 *
	 * @default true
	 */
	autoStart?: boolean

	/**
	 * Tick interval in milliseconds.
	 *
	 * @default 1000
	 */
	interval?: number

	/**
	 * Time display format.
	 *
	 * @default 'digital'
	 */
	format?: TimeFormat

	/**
	 * Duration for countdown variant (ms).
	 */
	durationMs?: number

	/**
	 * Text prefix before the time display.
	 */
	prefix?: string

	/**
	 * Text suffix after the time display.
	 */
	suffix?: string

	/**
	 * Show laps list (stopwatch only).
	 *
	 * @default false
	 */
	showLaps?: boolean

	/**
	 * Maximum number of laps to display.
	 *
	 * @default 10
	 */
	maxLapsDisplay?: number

	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Callback on each tick.
	 */
	onTick?: (elapsedMs: number) => void

	/**
	 * Callback when countdown completes.
	 */
	onComplete?: () => void

	/**
	 * Callback on lap.
	 */
	onLap?: (lap: ILap) => void
}
//#endregion Types

//#region Component
export const Timer: DefineComponent<TimerProps> = defineComponent({
	name: 'Timer',
	props: {
		variant: {
			type: String as PropType<TimerVariant>,
			default: 'timer',
		},
		autoStart: {
			type: Boolean,
			default: true,
		},
		interval: {
			type: Number,
			default: 1000,
		},
		format: {
			type: [String, Function] as PropType<TimeFormat>,
			default: 'digital',
		},
		durationMs: {
			type: Number,
			default: 0,
		},
		prefix: {
			type: String,
			default: undefined,
		},
		suffix: {
			type: String,
			default: undefined,
		},
		showLaps: {
			type: Boolean,
			default: false,
		},
		maxLapsDisplay: {
			type: Number,
			default: 10,
		},
		isDisabled: {
			type: Boolean,
			default: false,
		},
		onTick: {
			type: Function as PropType<(elapsedMs: number) => void>,
			default: undefined,
		},
		onComplete: {
			type: Function as PropType<() => void>,
			default: undefined,
		},
		onLap: {
			type: Function as PropType<(lap: ILap) => void>,
			default: undefined,
		},
	},
	setup(props) {
		const state = useTimerState({
			variant: props.variant,
			autoStart: props.autoStart,
			interval: props.interval,
			format: props.format,
			durationMs: props.durationMs,
			onTick: props.onTick,
			onComplete: props.onComplete,
			onLap: props.onLap,
		})

		useTimer({ isDisabled: toRef(props, 'isDisabled'), state })

		const theme = useComponentTheme<TimerRenderTheme>('Timer')
		const { styles, config } = theme ?? defaultTimerTheme

		return () => {
			const displayLaps = props.showLaps
				? state.laps.value.slice(-(props.maxLapsDisplay ?? 10))
				: []

			return wNodeToVue(
				renderTimer(
					{
						formattedTime: state.formattedTime.value,
						isRunning: state.isRunning.value,
						isPaused: state.isPaused.value,
						variant: state.variant,
						isComplete: state.isComplete.value,
						laps: displayLaps,
						prefix: props.prefix,
						suffix: props.suffix,
					},
					{ styles, config }
				)
			)
		}
	},
})
//#endregion Component

export { defaultTimerTheme as timerTheme, type TimerRenderTheme as TimerTheme }
export type { TimerProps as Props, TimerProps as IProps }

// packages/solid/src/components/Timer.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import {
	renderTimer,
	defaultTimerTheme,
	type TimerRenderTheme,
	type TimerVariant,
	type TimeFormat,
	type ILap,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { useTimerState } from '../composables/use-timer-state'
import { useTimer } from '../composables/use-timer'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export interface ITimerProps {
	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Timer variant: 'timer', 'countdown', or 'stopwatch'.
	 *
	 * @default 'timer'
	 */
	variant?: TimerVariant

	/**
	 * Duration in milliseconds (used for countdown).
	 *
	 * @default 0
	 */
	durationMs?: number

	/**
	 * Whether the timer starts automatically.
	 *
	 * @default true
	 */
	autoStart?: boolean

	/**
	 * Tick interval in milliseconds.
	 *
	 * @default 1000
	 */
	interval?: number

	/**
	 * Time display format.
	 *
	 * @default 'digital'
	 */
	format?: TimeFormat

	/**
	 * Prefix text displayed before the time.
	 */
	prefix?: string

	/**
	 * Suffix text displayed after the time.
	 */
	suffix?: string

	/**
	 * Whether lap list is shown (stopwatch only).
	 *
	 * @default true
	 */
	showLaps?: boolean

	/**
	 * Maximum number of laps to display.
	 *
	 * @default 10
	 */
	maxLapsDisplay?: number

	/**
	 * Called when the timer completes (countdown only).
	 */
	onComplete?: () => void

	/**
	 * Called on each tick with the current elapsed milliseconds.
	 */
	onTick?: (elapsedMs: number) => void

	/**
	 * Called when a new lap is recorded (stopwatch only).
	 */
	onLap?: (lap: ILap) => void
}
//#endregion Types

//#region Component
export function Timer(props: ITimerProps): JSX.Element {
	const [local] = splitProps(props, [
		'isDisabled',
		'variant',
		'durationMs',
		'autoStart',
		'interval',
		'format',
		'prefix',
		'suffix',
		'showLaps',
		'maxLapsDisplay',
		'onComplete',
		'onTick',
		'onLap',
	])

	const state = useTimerState({
		variant: local.variant,
		durationMs: local.durationMs,
		autoStart: local.autoStart,
		interval: local.interval,
		format: local.format,
		prefix: local.prefix,
		suffix: local.suffix,
		onComplete: local.onComplete,
		onTick: local.onTick,
		onLap: local.onLap,
	})

	useTimer({
		isDisabled: () => local.isDisabled,
		state,
		showLaps: local.showLaps,
	})

	const theme = useComponentTheme<TimerRenderTheme>('Timer')
	const { styles, config } = theme ?? defaultTimerTheme

	const wnode = createMemo(() =>
		renderTimer(
			{
				formattedTime: state.formattedTime(),
				isRunning: state.isRunning(),
				isPaused: state.isPaused(),
				variant: state.variant(),
				isComplete: state.isComplete(),
				laps: state.laps(),
				prefix: state.prefix,
				suffix: state.suffix,
			},
			{ styles, config }
		)
	)

	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}
//#endregion Component

export {
	defaultTimerTheme as timerTheme,
	type TimerRenderTheme as TimerTheme,
} from '@wolf-tui/shared'
