// packages/vue/src/components/UnorderedList.tsx
import {
	defineComponent,
	inject,
	provide,
	h,
	type PropType,
	type VNode,
} from 'vue'
import figures from 'figures'
import { Box, type BoxProps } from './Box'
import { Text, type TextProps } from './Text'
import { useComponentTheme, type IComponentTheme } from '../theme'
import {
	UnorderedListSymbol,
	UnorderedListItemSymbol,
} from '../context/symbols'
import { flatten } from '../utils/slots'
import { OrderedList } from './OrderedList'

//#region Types
export type UnorderedListContextProps = {
	/**
	 * Depth of the list.
	 */
	depth: number
}

export type UnorderedListItemContextProps = {
	/**
	 * Marker that's displayed before each list item.
	 */
	marker: string
}

export type UnorderedListTheme = {
	styles: {
		list: () => Partial<BoxProps>
		listItem: () => Partial<BoxProps>
		marker: () => Partial<TextProps>
		content: () => Partial<BoxProps>
	}
	config: () => {
		marker: string | string[]
	}
}

export interface UnorderedListProps {
	/**
	 * List items.
	 */
	children?: VNode[]
}

export interface UnorderedListItemProps {
	/**
	 * List item content.
	 */
	children?: VNode[]
}
//#endregion Types

//#region Constants
const defaultMarker = figures.line
const defaultMarkers = [figures.bullet, figures.line, figures.pointer]
//#endregion Constants

//#region Theme
export const unorderedListTheme = {
	styles: {
		list: (): Partial<BoxProps> => ({
			style: {
				flexDirection: 'column',
			},
		}),
		listItem: (): Partial<BoxProps> => ({
			style: {
				flexDirection: 'row',
			},
		}),
		marker: (): Partial<TextProps> => ({
			style: {
				color: 'green',
			},
		}),
		content: (): Partial<BoxProps> => ({
			style: {
				flexDirection: 'column',
				marginLeft: 1,
			},
		}),
	},
	config() {
		return {
			marker: defaultMarkers,
		}
	},
} satisfies IComponentTheme
//#endregion Theme

//#region UnorderedListItem Component
export const UnorderedListItem = defineComponent({
	name: 'UnorderedListItem',
	props: {
		children: {
			type: Array as PropType<VNode[]>,
			default: undefined,
		},
	},
	setup(props, { slots }) {
		const itemContext = inject<UnorderedListItemContextProps>(
			UnorderedListItemSymbol,
			{ marker: defaultMarker }
		)

		return () => {
			const theme = useComponentTheme<UnorderedListTheme>('UnorderedList')
			const styles = theme?.styles ?? unorderedListTheme.styles

			const children = slots.default?.() ?? props.children

			return (
				<Box {...styles.listItem()}>
					<Text {...styles.marker()}>{itemContext.marker}</Text>
					<Box {...styles.content()}>{children}</Box>
				</Box>
			)
		}
	},
})
//#endregion UnorderedListItem Component

//#region UnorderedList Component
const UnorderedListComponent = defineComponent({
	name: 'UnorderedList',
	props: {
		children: {
			type: Array as PropType<VNode[]>,
			default: undefined,
		},
	},
	setup(props, { slots }) {
		const parentContext = inject<UnorderedListContextProps>(
			UnorderedListSymbol,
			{ depth: 0 }
		)

		// Compute contexts and provide them in setup
		const theme = useComponentTheme<UnorderedListTheme>('UnorderedList')
		const config = theme?.config ?? unorderedListTheme.config

		// Determine marker based on depth
		const { marker: markerConfig } = config()
		let marker: string

		if (typeof markerConfig === 'string') {
			marker = markerConfig
		} else if (Array.isArray(markerConfig)) {
			marker =
				markerConfig[parentContext.depth] ??
				markerConfig.at(-1) ??
				defaultMarker
		} else {
			marker = defaultMarker
		}

		// Provide contexts for nested lists and items
		const listContext: UnorderedListContextProps = {
			depth: parentContext.depth + 1,
		}
		const itemContext: UnorderedListItemContextProps = { marker }

		provide<UnorderedListContextProps>(UnorderedListSymbol, listContext)
		provide<UnorderedListItemContextProps>(UnorderedListItemSymbol, itemContext)

		return () => {
			const styles = theme?.styles ?? unorderedListTheme.styles
			const children = slots.default?.() ?? props.children ?? []
			const flatChildren = flatten(
				Array.isArray(children) ? children : [children]
			)

			const wrappedChildren = flatChildren.map((child) => {
				if (
					child &&
					typeof child === 'object' &&
					'type' in child &&
					(child.type === UnorderedListItem ||
						(child.type as any)?.name === 'UnorderedListItem' ||
						child.type === UnorderedListComponent ||
						(child.type as any)?.name === 'UnorderedList' ||
						child.type === OrderedList ||
						(child.type as any)?.name === 'OrderedList')
				) {
					return child
				}

				return h(UnorderedListItem, null, () => child)
			})

			const result = <Box {...styles.list()}>{wrappedChildren}</Box>
			return result
		}
	},
})

export const UnorderedList = /*#__PURE__*/ Object.assign(
	UnorderedListComponent,
	{
		Item: UnorderedListItem,
	}
)
//#endregion UnorderedList Component

export type { UnorderedListProps as Props, UnorderedListProps as IProps }

// packages/solid/src/components/UnorderedList.tsx
import { type JSX, createContext, useContext } from 'solid-js'
import figures from 'figures'
import { Box } from './Box'
import { Text } from './Text'

//#region Types
export interface IUnorderedListItemProps {
	children: JSX.Element
}

export interface IUnorderedListProps {
	children: JSX.Element
}
//#endregion Types

//#region Context
// WHY: local contexts — no need to export to symbols.ts, scoped to this component tree
const UnorderedListCtx = /*#__PURE__*/ createContext<{ depth: number }>({
	depth: 0,
})
const UnorderedListItemCtx = /*#__PURE__*/ createContext<{ marker: string }>({
	marker: '',
})
//#endregion Context

//#region UnorderedListItem Component
export function UnorderedListItem(props: IUnorderedListItemProps): JSX.Element {
	const listItemCtx = useContext(UnorderedListItemCtx)

	return (
		<Box style={{ flexDirection: 'row' }}>
			<Text style={{ color: 'green' }}>{listItemCtx.marker}</Text>
			<Box style={{ flexDirection: 'column', marginLeft: 1 }}>
				{props.children}
			</Box>
		</Box>
	)
}
//#endregion UnorderedListItem Component

//#region UnorderedList Component
function UnorderedListBase(props: IUnorderedListProps): JSX.Element {
	const listCtx = useContext(UnorderedListCtx)
	const depth = listCtx.depth

	const markers = [figures.bullet, figures.line, figures.pointer]
	const marker = markers[depth % markers.length] ?? figures.bullet

	return (
		<UnorderedListCtx.Provider value={{ depth: depth + 1 }}>
			<UnorderedListItemCtx.Provider value={{ marker }}>
				<Box style={{ flexDirection: 'column' }}>{props.children}</Box>
			</UnorderedListItemCtx.Provider>
		</UnorderedListCtx.Provider>
	)
}

export const UnorderedList = /*#__PURE__*/ Object.assign(UnorderedListBase, {
	Item: UnorderedListItem,
})
//#endregion UnorderedList Component

export type { IUnorderedListProps as Props, IUnorderedListProps as IProps }
