// examples/svelte_invaders/src/screens/Game.svelte
<script lang="ts">
	import { onDestroy } from 'svelte'
	import { Box, Text, useInput, useStdin } from '@wolfie/svelte'
	import GameCanvas from '../components/GameCanvas.svelte'
	import HUD from '../components/HUD.svelte'
	import KillLog from '../components/KillLog.svelte'
	import Controls from '../components/Controls.svelte'
	import { useGameLoop } from '../composables/useGameLoop.svelte'
	import type { State, Screen } from '../composables/useInvaders.svelte'
	import { ALIEN_SHOOT_INTERVAL } from '../constants'
	import { debugLog } from '../debug'
	import { BRAND } from '../theme'

	//#region Props
	let { gameState, onTick, onMovePlayer, onShoot, onAlienShoot, onPause, onNextWave, onNavigate }: {
		gameState: State
		onTick: () => void
		onMovePlayer: (dx: number) => void
		onShoot: () => void
		onAlienShoot: () => void
		onPause: () => void
		onNextWave: () => void
		onNavigate: (screen: Screen) => void
	} = $props()
	//#endregion Props

	const { isRawModeSupported } = useStdin()

	//#region FPS Calculation
	let fps = $state(0)
	let lastFrameTime = Date.now()
	let frameCount = 0

	$effect(() => {
		void gameState.frame
		frameCount++
		const now = Date.now()
		const elapsed = now - lastFrameTime

		if (elapsed >= 1000) {
			fps = Math.round((frameCount * 1000) / elapsed)
			frameCount = 0
			lastFrameTime = now
		}
	})
	//#endregion FPS Calculation

	//#region Game Loop
	let isRunning = $derived(!gameState.paused && !gameState.waveTransition)
	useGameLoop({
		onTick: () => onTick(),
		isRunning: () => isRunning,
	})
	//#endregion Game Loop

	//#region Alien Shooting
	let alienShootInterval: ReturnType<typeof setInterval> | null = null

	function startAlienShooting() {
		if (alienShootInterval) return
		alienShootInterval = setInterval(() => {
			onAlienShoot()
		}, ALIEN_SHOOT_INTERVAL)
	}

	function stopAlienShooting() {
		if (alienShootInterval) {
			clearInterval(alienShootInterval)
			alienShootInterval = null
		}
	}

	$effect(() => {
		if (gameState.paused || gameState.waveTransition) {
			stopAlienShooting()
		} else {
			startAlienShooting()
		}
	})

	onDestroy(() => {
		stopAlienShooting()
	})
	//#endregion Alien Shooting

	//#region Wave Transition
	$effect(() => {
		if (gameState.waveTransition) {
			const timer = setTimeout(() => {
				onNextWave()
			}, 2000)
			return () => clearTimeout(timer)
		}
	})
	//#endregion Wave Transition

	//#region Input Handling
	useInput((input, key) => {
		if (input === 'p') {
			onPause()
			return
		}

		if (input === 'q') {
			onNavigate('menu')
			return
		}

		if (gameState.paused) return

		if (key.leftArrow) {
			onMovePlayer(-1)
		} else if (key.rightArrow) {
			onMovePlayer(1)
		} else if (input === ' ') {
			debugLog('Input: SPACE pressed')
			onShoot()
		}
	})
	//#endregion Input Handling

	//#region Computed
	let pauseMarginTop = $derived(Math.floor(gameState.board.height / 2))
	//#endregion Computed
</script>

{#if gameState.waveTransition}
	<!-- Wave transition screen -->
	<Box
		style={{
			width: '100vw',
			height: '100vh',
			flexDirection: 'column',
			alignItems: 'center',
			justifyContent: 'center',
			backgroundColor: BRAND.bgAccent,
		}}
	>
		<Box
			style={{
				flexDirection: 'column',
				alignItems: 'center',
				borderStyle: 'round',
				borderColor: BRAND.success,
				paddingLeft: 2,
				paddingRight: 2,
				paddingTop: 1,
				paddingBottom: 1,
			}}
		>
			<Text style={{ color: BRAND.success }} className="font-bold">
				✓ Wave Complete!
			</Text>
			<Text>Excellent work, Commander! Preparing next wave…</Text>
		</Box>

		<Box style={{ marginTop: 2 }}>
			<Text className="text-cyan">
				Loading Wave {gameState.wave + 1}…
			</Text>
		</Box>

		<Box style={{ marginTop: 2 }}>
			<Text className="text-yellow font-bold">
				Score: {gameState.score}
			</Text>
		</Box>
	</Box>
{:else}
	<!-- Main game screen -->
	<Box
		style={{
			width: '100vw',
			height: '100vh',
			flexDirection: 'column',
			backgroundColor: BRAND.bgDark,
		}}
	>
		<!-- Header -->
		<Box
			style={{
				flexShrink: 0,
				paddingLeft: 1,
				paddingRight: 1,
				backgroundColor: BRAND.bgDark,
			}}
		>
			<HUD
				score={gameState.score}
				lives={gameState.lives}
				wave={gameState.wave}
				showFps={gameState.settings.showFps}
				{fps}
			/>
		</Box>

		<!-- Main game area -->
		<Box
			style={{
				flexGrow: 1,
				flexDirection: 'column',
				minHeight: 0,
				overflow: 'hidden',
			}}
		>
			<GameCanvas
				aliens={gameState.aliens}
				bullets={gameState.bullets}
				shields={gameState.shields}
				playerX={gameState.player.x}
				frame={gameState.frame}
				boardWidth={gameState.board.width}
				boardHeight={gameState.board.height}
			/>
		</Box>

		<!-- Pause indicator -->
		{#if gameState.paused}
			<Box
				style={{
					position: 'absolute',
					width: '100vw',
					justifyContent: 'center',
					marginTop: pauseMarginTop,
				}}
			>
				<Text className="text-yellow font-bold bg-red">
					{'  '}══ PAUSED ══ (P to resume){'  '}
				</Text>
			</Box>
		{/if}

		<!-- Footer -->
		<Box
			style={{
				flexShrink: 0,
				flexDirection: 'row',
				justifyContent: 'space-between',
				paddingLeft: 2,
				paddingRight: 2,
				backgroundColor: BRAND.bgAccent,
				paddingTop: 1,
			}}
		>
			<KillLog kills={gameState.kills.slice(-3)} />
			<Controls />
		</Box>

		{#if !isRawModeSupported}
			<Box
				style={{
					borderStyle: 'round',
					borderColor: BRAND.warning,
					paddingLeft: 1,
					paddingRight: 1,
				}}
			>
				<Text style={{ color: BRAND.warning }}>
					⚠ Raw mode not supported — input may be limited
				</Text>
			</Box>
		{/if}
	</Box>
{/if}

// examples/angular_invaders/src/screens/game.component.ts
import {
	Component,
	ChangeDetectionStrategy,
	inject,
	signal,
	effect,
} from '@angular/core'
import {
	BoxComponent,
	TextComponent,
	AlertComponent,
	SpinnerComponent,
	StdinService,
	injectInput,
} from '@wolfie/angular'
import { InvadersService } from '../services/invaders.service'
import { GameCanvasComponent } from '../components/game-canvas.component'
import { HudComponent } from '../components/hud.component'
import { KillLogComponent } from '../components/kill-log.component'
import { ControlsComponent } from '../components/controls.component'
import { BRAND } from '../theme'

//#region GameComponent
@Component({
	selector: 'app-game',
	standalone: true,
	imports: [
		BoxComponent,
		TextComponent,
		AlertComponent,
		SpinnerComponent,
		GameCanvasComponent,
		HudComponent,
		KillLogComponent,
		ControlsComponent,
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		@if (invaders.waveTransition()) {
			<w-box
				[style]="{
					width: '100vw',
					height: '100vh',
					flexDirection: 'column',
					alignItems: 'center',
					justifyContent: 'center',
					backgroundColor: brand.bgAccent,
				}"
			>
				<w-alert
					variant="success"
					title="Wave Complete!"
					message="Excellent work, Commander! Preparing next wave…"
				/>

				<w-box [style]="{ marginTop: 2 }">
					<w-spinner type="dots" />
					<w-text className="text-cyan ml-2"
						>{{ ' ' }}Loading Wave {{ invaders.state().wave + 1 }}…</w-text
					>
				</w-box>

				<w-box [style]="{ marginTop: 2 }">
					<w-text className="text-yellow font-bold"
						>Score: {{ invaders.state().score }}</w-text
					>
				</w-box>
			</w-box>
		} @else {
			<w-box
				[style]="{
					width: '100vw',
					height: '100vh',
					flexDirection: 'column',
					backgroundColor: brand.bgDark,
				}"
			>
				<w-box
					[style]="{
						flexShrink: 0,
						paddingLeft: 1,
						paddingRight: 1,
						backgroundColor: brand.bgDark,
					}"
				>
					<app-hud />
				</w-box>

				<w-box
					[style]="{
						flexGrow: 1,
						flexDirection: 'column',
						minHeight: 0,
						overflow: 'hidden',
					}"
				>
					<app-game-canvas />
				</w-box>

				@if (invaders.paused()) {
					<w-box
						[style]="{
							position: 'absolute',
							width: '100vw',
							justifyContent: 'center',
							marginTop: pauseOverlayTop(),
						}"
					>
						<w-text className="text-yellow font-bold bg-red"
							>{{ '  ' }}══ PAUSED ══ (P to resume){{ '  ' }}</w-text
						>
					</w-box>
				}

				<w-box
					[style]="{
						flexShrink: 0,
						flexDirection: 'row',
						justifyContent: 'space-between',
						paddingLeft: 2,
						paddingRight: 2,
						backgroundColor: brand.bgAccent,
						paddingTop: 1,
					}"
				>
					<app-kill-log />
					<app-controls />
				</w-box>

				@if (!isRawModeSupported) {
					<w-alert variant="warning" title="Warning">
						Raw mode not supported — input may be limited
					</w-alert>
				}
			</w-box>
		}
	`,
})
export class GameComponent {
	readonly brand = BRAND
	readonly invaders = inject(InvadersService)
	readonly isRawModeSupported: boolean

	//#region FPS Tracking
	readonly fps = signal(0)
	private lastFrameTime = Date.now()
	private frameCount = 0
	//#endregion FPS Tracking

	//#region Computed
	readonly pauseOverlayTop = () =>
		Math.floor(this.invaders.state().board.height / 2)
	//#endregion Computed

	constructor() {
		const stdinService = inject(StdinService)
		this.isRawModeSupported = stdinService.isRawModeSupported

		// FPS calculation via effect on frame changes
		effect(() => {
			// eslint-disable-next-line @typescript-eslint/no-unused-vars
			const _frame = this.invaders.state().frame
			this.frameCount++
			const now = Date.now()
			const elapsed = now - this.lastFrameTime

			if (elapsed >= 1000) {
				this.fps.set(Math.round((this.frameCount * 1000) / elapsed))
				this.frameCount = 0
				this.lastFrameTime = now
			}
		})

		// Input handling
		injectInput(
			(input, key) => {
				if (input === 'p') {
					this.invaders.pause()
					return
				}
				if (input === 'q') {
					this.invaders.navigate('menu')
					return
				}
				if (this.invaders.paused()) return

				if (key.leftArrow) {
					this.invaders.movePlayer(-1)
				} else if (key.rightArrow) {
					this.invaders.movePlayer(1)
				} else if (input === ' ') {
					this.invaders.shoot()
				}
			},
			{ isActive: () => this.invaders.screen() === 'game' }
		)
	}
}
//#endregion GameComponent
