// packages/svelte/src/components/Alert.svelte
<script lang="ts">
	import {
		renderAlert,
		defaultAlertTheme,
		type AlertRenderTheme,
	} from '@wolfie/shared'
	import { mountWNode } from '../wnode/wnode-to-svelte.js'
	import { useComponentTheme } from '../theme/index.js'

	//#region Types
	type AlertVariant = 'info' | 'success' | 'error' | 'warning'
	//#endregion Types

	let { variant, title, children }: {
		variant: AlertVariant
		title?: string
		children?: string
	} = $props()

	const theme = useComponentTheme<AlertRenderTheme>('Alert')
	const { styles, config } = theme ?? defaultAlertTheme

	let wnode = $derived(renderAlert(
		{ variant, title, message: String(children ?? '') },
		{ styles, config }
	))
</script>

<wolfie-box use:mountWNode={wnode}></wolfie-box>

// packages/vue/src/components/Alert.tsx
import { defineComponent, type PropType, type VNode } from 'vue'
import {
	renderAlert,
	defaultAlertTheme,
	type AlertRenderTheme,
	type AlertVariant,
} from '@wolfie/shared'
import { wNodeToVue } from '../wnode/wnode-to-vue'

//#region Types
export { type AlertVariant }

export interface AlertProps {
	/**
	 * Message content.
	 */
	children?: VNode | VNode[]

	/**
	 * Variant, which determines the color of the alert.
	 */
	variant: AlertVariant

	/**
	 * Title to show above the message.
	 */
	title?: string
}
//#endregion Types

//#region Helpers
function extractTextFromSlot(children: VNode[] | undefined): string {
	if (!children || children.length === 0) return ''
	const firstChild = children[0]
	if (!firstChild) return ''
	if (typeof firstChild === 'string') return firstChild
	if (typeof firstChild === 'object' && 'children' in firstChild) {
		const nodeChildren = firstChild.children
		if (typeof nodeChildren === 'string') return nodeChildren
		if (Array.isArray(nodeChildren) && nodeChildren.length > 0) {
			const text = nodeChildren[0]
			if (typeof text === 'string') return text
		}
	}
	return ''
}
//#endregion Helpers

//#region Component
export const Alert = defineComponent({
	name: 'Alert',
	props: {
		variant: {
			type: String as PropType<AlertVariant>,
			required: true,
		},
		title: {
			type: String,
			default: undefined,
		},
	},
	setup(props, { slots }) {
		const { styles, config } = defaultAlertTheme

		return () => {
			const { variant, title } = props
			const message = extractTextFromSlot(slots.default?.())
			return wNodeToVue(renderAlert({ variant, title, message }, { styles, config }))
		}
	},
})
//#endregion Component

export { defaultAlertTheme as alertTheme, type AlertRenderTheme as AlertTheme }
export type { AlertProps as Props, AlertProps as IProps }
