// packages/solid/src/components/FilePicker.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import {
	renderFilePicker,
	defaultFilePickerTheme,
	type FilePickerRenderTheme,
	type FileTypeFilter,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { useFilePickerState } from '../composables/use-file-picker-state'
import { useFilePicker } from '../composables/use-file-picker'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export interface IFilePickerProps {
	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Initial directory path.
	 *
	 * @default '.'
	 */
	initialPath?: string

	/**
	 * Allow selecting multiple files.
	 *
	 * @default false
	 */
	multiSelect?: boolean

	/**
	 * Filter by file type.
	 *
	 * @default 'all'
	 */
	fileTypes?: FileTypeFilter

	/**
	 * Show hidden files (dotfiles).
	 *
	 * @default false
	 */
	showHidden?: boolean

	/**
	 * Show file size details.
	 *
	 * @default false
	 */
	showDetails?: boolean

	/**
	 * Maximum visible entries.
	 *
	 * @default 10
	 */
	maxHeight?: number

	/**
	 * Called when file selection is confirmed.
	 */
	onSelect?: (paths: string[]) => void

	/**
	 * Called on every selection toggle (Space key). Fires in real-time
	 * as the user toggles items, unlike onSelect which fires on confirmation.
	 */
	onSelectionChange?: (paths: string[]) => void

	/**
	 * Called on cancel (Escape).
	 */
	onCancel?: () => void

	/**
	 * Called when the current directory changes.
	 */
	onDirectoryChange?: (path: string) => void
}
//#endregion Types

//#region Component
export function FilePicker(props: IFilePickerProps): JSX.Element {
	const [local] = splitProps(props, [
		'isDisabled',
		'initialPath',
		'multiSelect',
		'fileTypes',
		'showHidden',
		'showDetails',
		'maxHeight',
		'onSelect',
		'onSelectionChange',
		'onCancel',
		'onDirectoryChange',
	])

	const state = useFilePickerState({
		initialPath: local.initialPath,
		multiSelect: local.multiSelect,
		fileTypes: local.fileTypes,
		showHidden: local.showHidden,
		showDetails: local.showDetails,
		maxHeight: local.maxHeight,
		onSelect: local.onSelect,
		onSelectionChange: local.onSelectionChange,
		onDirectoryChange: local.onDirectoryChange,
	})

	useFilePicker({
		isDisabled: () => local.isDisabled,
		onCancel: local.onCancel,
		state,
	})

	const theme = useComponentTheme<FilePickerRenderTheme>('FilePicker')
	const { styles, config } = theme ?? defaultFilePickerTheme

	const wnode = createMemo(() =>
		renderFilePicker(
			{
				currentPath: state.currentPath(),
				visibleEntries: state.visibleEntries(),
				mode: state.mode(),
				filterText: state.filterText(),
				multiSelect: state.multiSelect(),
				showDetails: state.showDetails(),
				errorMessage: state.errorMessage(),
				hasScrollUp: state.hasScrollUp(),
				hasScrollDown: state.hasScrollDown(),
				scrollUpCount: state.scrollUpCount(),
				scrollDownCount: state.scrollDownCount(),
			},
			{ styles, config }
		)
	)

	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}
//#endregion Component

export {
	defaultFilePickerTheme as filePickerTheme,
	type FilePickerRenderTheme as FilePickerTheme,
} from '@wolf-tui/shared'

// packages/vue/src/components/FilePicker.tsx
import {
	defineComponent,
	toRef,
	type PropType,
	type DefineComponent,
} from 'vue'
import {
	renderFilePicker,
	defaultFilePickerTheme,
	type FilePickerRenderTheme,
	type FileTypeFilter,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { useFilePickerState } from '../composables/use-file-picker-state'
import { useFilePicker } from '../composables/use-file-picker'
import { wNodeToVue } from '../wnode/wnode-to-vue'

//#region Types
export interface FilePickerProps {
	/**
	 * Initial directory path.
	 *
	 * @default '.'
	 */
	initialPath?: string

	/**
	 * Allow multiple file selection.
	 *
	 * @default false
	 */
	multiSelect?: boolean

	/**
	 * Filter by file type.
	 *
	 * @default 'all'
	 */
	fileTypes?: FileTypeFilter

	/**
	 * Show hidden files (dotfiles).
	 *
	 * @default false
	 */
	showHidden?: boolean

	/**
	 * Show file details (size).
	 *
	 * @default false
	 */
	showDetails?: boolean

	/**
	 * Maximum visible entries.
	 *
	 * @default 10
	 */
	maxHeight?: number

	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Callback when selection is confirmed.
	 */
	onSelect?: (selectedPaths: string[]) => void

	/**
	 * Callback on every selection toggle (Space key). Fires in real-time
	 * as the user toggles items, unlike onSelect which fires on confirmation.
	 */
	onSelectionChange?: (paths: string[]) => void

	/**
	 * Callback on cancel (Escape).
	 */
	onCancel?: () => void

	/**
	 * Callback when current directory changes.
	 */
	onDirectoryChange?: (path: string) => void

	/**
	 * Callback on error.
	 */
	onError?: (error: string) => void
}
//#endregion Types

//#region Component
export const FilePicker: DefineComponent<FilePickerProps> = defineComponent({
	name: 'FilePicker',
	props: {
		initialPath: {
			type: String,
			default: '.',
		},
		multiSelect: {
			type: Boolean,
			default: false,
		},
		fileTypes: {
			type: String as PropType<FileTypeFilter>,
			default: 'all',
		},
		showHidden: {
			type: Boolean,
			default: false,
		},
		showDetails: {
			type: Boolean,
			default: false,
		},
		maxHeight: {
			type: Number,
			default: 10,
		},
		isDisabled: {
			type: Boolean,
			default: false,
		},
		onSelect: {
			type: Function as PropType<(selectedPaths: string[]) => void>,
			default: undefined,
		},
		onSelectionChange: {
			type: Function as PropType<(paths: string[]) => void>,
			default: undefined,
		},
		onCancel: {
			type: Function as PropType<() => void>,
			default: undefined,
		},
		onDirectoryChange: {
			type: Function as PropType<(path: string) => void>,
			default: undefined,
		},
		onError: {
			type: Function as PropType<(error: string) => void>,
			default: undefined,
		},
	},
	setup(props) {
		const state = useFilePickerState({
			initialPath: props.initialPath,
			multiSelect: props.multiSelect,
			fileTypes: props.fileTypes,
			showHidden: props.showHidden,
			showDetails: props.showDetails,
			maxHeight: props.maxHeight,
			onSelect: props.onSelect,
			onSelectionChange: props.onSelectionChange,
			onDirectoryChange: props.onDirectoryChange,
			onError: props.onError,
		})

		useFilePicker({
			isDisabled: toRef(props, 'isDisabled'),
			onCancel: props.onCancel,
			state,
		})

		const theme = useComponentTheme<FilePickerRenderTheme>('FilePicker')
		const { styles, config } = theme ?? defaultFilePickerTheme

		return () => {
			return wNodeToVue(
				renderFilePicker(
					{
						currentPath: state.currentPath.value,
						visibleEntries: state.visibleEntries.value,
						mode: state.mode.value,
						filterText: state.filterText.value,
						multiSelect: state.multiSelect,
						showDetails: state.showDetails,
						errorMessage: state.errorMessage.value,
						hasScrollUp: state.hasScrollUp.value,
						hasScrollDown: state.hasScrollDown.value,
						scrollUpCount: state.scrollUpCount.value,
						scrollDownCount: state.scrollDownCount.value,
					},
					{ styles, config }
				)
			)
		}
	},
})
//#endregion Component

export {
	defaultFilePickerTheme as filePickerTheme,
	type FilePickerRenderTheme as FilePickerTheme,
}
export type { FilePickerProps as Props, FilePickerProps as IProps }
