// packages/solid/src/components/Newline.tsx
import { type JSX } from 'solid-js'
import { renderNewline } from '@wolfie/shared'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export interface NewlineProps {
	count?: number
}
//#endregion Types

export function Newline(props: NewlineProps): JSX.Element {
	return (() =>
		wNodeToSolid(
			renderNewline({ count: props.count ?? 1 })
		)) as unknown as JSX.Element
}

export type { NewlineProps as Props, NewlineProps as IProps }

// packages/vue/src/components/Newline.tsx
import { defineComponent, type PropType } from 'vue'
import { renderNewline } from '@wolfie/shared'
import { wNodeToVue } from '../wnode/wnode-to-vue'

//#region Types
export interface NewlineProps {
	/**
	 * Number of newlines to insert.
	 * @default 1
	 */
	count?: number
}
//#endregion Types

/**
 * Adds one or more newline (`\n`) characters. Must be used within `<Text>` components.
 */
export const Newline = defineComponent({
	name: 'Newline',
	props: {
		count: {
			type: Number as PropType<number>,
			default: 1,
		},
	},
	setup(props) {
		return () => wNodeToVue(renderNewline({ count: props.count ?? 1 }))
	},
})

export type { NewlineProps as Props, NewlineProps as IProps }
