// packages/angular/src/components/progress-bar/progress-bar.component.ts
import type { AfterViewInit } from '@angular/core'
import {
	Component,
	Input,
	signal,
	computed,
	ElementRef,
	inject,
	ChangeDetectionStrategy,
} from '@angular/core'
import { measureElement } from '@wolfie/core'
import {
	renderProgressBar,
	defaultProgressBarTheme,
	type ProgressBarRenderTheme,
} from '@wolfie/shared'
import { WNodeOutletComponent } from '../wnode-outlet/wnode-outlet.component'

//#region ProgressBarComponent
/**
 * `<w-progress-bar>` displays a visual progress indicator.
 */
@Component({
	selector: 'w-progress-bar',
	standalone: true,
	imports: [WNodeOutletComponent],
	template: `<w-wnode-outlet [node]="wnode()" />`,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProgressBarComponent implements AfterViewInit {
	@Input({ required: true }) value!: number

	private readonly width = signal(0)
	// WHY: inject(ElementRef) to measure host element width in ngAfterViewInit
	private readonly el = inject(ElementRef)

	protected readonly wnode = computed(() =>
		renderProgressBar(
			{ value: this.value, width: this.width() },
			defaultProgressBarTheme
		)
	)

	ngAfterViewInit(): void {
		const dimensions = measureElement(this.el.nativeElement)
		this.width.set(dimensions.width)
	}
}
//#endregion ProgressBarComponent

export { defaultProgressBarTheme as progressBarTheme }
export type { ProgressBarRenderTheme as ProgressBarProps }

// packages/vue/src/components/ProgressBar.tsx
import { defineComponent, ref, h } from 'vue'
import { measureElement, type DOMElement } from '@wolfie/core'
import {
	renderProgressBar,
	defaultProgressBarTheme,
	type ProgressBarRenderTheme,
} from '@wolfie/shared'
import { useComponentTheme } from '../theme'
import { wNodeToVue } from '../wnode/wnode-to-vue'

//#region ProgressBarComponent
export const ProgressBar = defineComponent({
	name: 'ProgressBar',
	props: {
		value: { type: Number, required: true as const },
	},
	setup(props) {
		const width = ref(0)

		const setRef = (el: unknown) => {
			const domEl = el as DOMElement | null
			if (domEl) {
				const dimensions = measureElement(domEl)
				if (dimensions.width !== width.value) {
					width.value = dimensions.width
				}
			}
		}

		const theme =
			useComponentTheme<ProgressBarRenderTheme>('ProgressBar') ??
			defaultProgressBarTheme

		return () =>
			// WHY: wolfie-box wrapper owns container style + ref for measurement.
			// renderProgressBar returns bars only (no container).
			h('wolfie-box', { ref: setRef, style: { flexGrow: 1, minWidth: 0 } }, [
				wNodeToVue(
					renderProgressBar({ value: props.value, width: width.value }, theme)
				),
			])
	},
})
//#endregion ProgressBarComponent

export type ProgressBarProps = { value: number }
export type { ProgressBarRenderTheme as ProgressBarTheme }
export { defaultProgressBarTheme as progressBarTheme }
export type { ProgressBarProps as Props, ProgressBarProps as IProps }
