// packages/solid/src/components/TreeView.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import {
	renderTreeView,
	defaultTreeViewTheme,
	type TreeViewRenderTheme,
	type TreeViewSelectionMode,
	type ITreeNode,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { useTreeViewState } from '../composables/use-tree-view-state'
import { useTreeView } from '../composables/use-tree-view'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export interface ITreeViewProps<T = Record<string, unknown>> {
	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Tree data.
	 */
	data: ITreeNode<T>[]

	/**
	 * Selection mode.
	 *
	 * @default 'none'
	 */
	selectionMode?: TreeViewSelectionMode

	/**
	 * Default expanded node IDs. Pass 'all' to expand everything.
	 */
	defaultExpanded?: ReadonlySet<string> | 'all'

	/**
	 * Default selected node IDs.
	 */
	defaultSelected?: ReadonlySet<string>

	/**
	 * Number of visible nodes in the viewport.
	 */
	visibleNodeCount?: number

	/**
	 * Called when selection changes.
	 */
	onSelect?: (selectedIds: ReadonlySet<string>) => void

	/**
	 * Called when a node is expanded.
	 */
	onExpand?: (nodeId: string) => void

	/**
	 * Called when a node is collapsed.
	 */
	onCollapse?: (nodeId: string) => void
}
//#endregion Types

//#region Component
export function TreeView<T = Record<string, unknown>>(
	props: ITreeViewProps<T>
): JSX.Element {
	const [local] = splitProps(props, [
		'isDisabled',
		'data',
		'selectionMode',
		'defaultExpanded',
		'defaultSelected',
		'visibleNodeCount',
		'onSelect',
		'onExpand',
		'onCollapse',
	])

	const state = useTreeViewState({
		data: local.data,
		selectionMode: local.selectionMode,
		defaultExpanded: local.defaultExpanded,
		defaultSelected: local.defaultSelected,
		visibleNodeCount: local.visibleNodeCount,
		onSelect: local.onSelect,
		onExpand: local.onExpand,
		onCollapse: local.onCollapse,
	})

	useTreeView({ isDisabled: () => local.isDisabled, state })

	const theme = useComponentTheme<TreeViewRenderTheme>('TreeView')
	const { styles, config } = theme ?? defaultTreeViewTheme

	const wnode = createMemo(() =>
		renderTreeView(
			{
				visibleNodes: state.visibleNodes(),
				selectionMode: state.selectionMode(),
				hasScrollUp: state.hasScrollUp(),
				hasScrollDown: state.hasScrollDown(),
				scrollUpCount: state.scrollUpCount(),
				scrollDownCount: state.scrollDownCount(),
			},
			{ styles, config }
		)
	)

	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}
//#endregion Component

export {
	defaultTreeViewTheme as treeViewTheme,
	type TreeViewRenderTheme as TreeViewTheme,
} from '@wolf-tui/shared'

// packages/vue/src/components/TreeView.tsx
import {
	defineComponent,
	toRef,
	type PropType,
	type DefineComponent,
} from 'vue'
import {
	renderTreeView,
	defaultTreeViewTheme,
	type TreeViewRenderTheme,
	type TreeViewSelectionMode,
	type ITreeNode,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { useTreeViewState } from '../composables/use-tree-view-state'
import { useTreeView } from '../composables/use-tree-view'
import { wNodeToVue } from '../wnode/wnode-to-vue'

//#region Types
export interface TreeViewProps {
	/**
	 * Tree data.
	 */
	data: ITreeNode[]

	/**
	 * Selection mode: 'none' | 'single' | 'multiple'.
	 *
	 * @default 'none'
	 */
	selectionMode?: TreeViewSelectionMode

	/**
	 * Default expanded node IDs.
	 */
	defaultExpanded?: ReadonlySet<string> | 'all'

	/**
	 * Default selected node IDs.
	 */
	defaultSelected?: ReadonlySet<string>

	/**
	 * Number of visible nodes.
	 *
	 * @default 10
	 */
	visibleNodeCount?: number

	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Callback when selection changes.
	 */
	onSelect?: (selectedIds: ReadonlySet<string>) => void

	/**
	 * Callback when focused node changes.
	 */
	onFocusChange?: (focusedId: string | undefined) => void

	/**
	 * Callback to load children for a node (async tree).
	 */
	loadChildren?: (nodeId: string) => Promise<ITreeNode[]>
}
//#endregion Types

//#region Component
export const TreeView: DefineComponent<TreeViewProps> = defineComponent({
	name: 'TreeView',
	props: {
		data: {
			type: Array as PropType<ITreeNode[]>,
			required: true,
		},
		selectionMode: {
			type: String as PropType<TreeViewSelectionMode>,
			default: 'none',
		},
		defaultExpanded: {
			type: [Object, String] as PropType<ReadonlySet<string> | 'all'>,
			default: undefined,
		},
		defaultSelected: {
			type: Object as PropType<ReadonlySet<string>>,
			default: undefined,
		},
		visibleNodeCount: {
			type: Number,
			default: 10,
		},
		isDisabled: {
			type: Boolean,
			default: false,
		},
		onSelect: {
			type: Function as PropType<(selectedIds: ReadonlySet<string>) => void>,
			default: undefined,
		},
		onFocusChange: {
			type: Function as PropType<(focusedId: string | undefined) => void>,
			default: undefined,
		},
		loadChildren: {
			type: Function as PropType<(nodeId: string) => Promise<ITreeNode[]>>,
			default: undefined,
		},
	},
	setup(props) {
		const state = useTreeViewState({
			data: props.data,
			selectionMode: props.selectionMode,
			defaultExpanded: props.defaultExpanded,
			defaultSelected: props.defaultSelected,
			visibleNodeCount: props.visibleNodeCount,
			onSelect: props.onSelect,
			onFocusChange: props.onFocusChange,
			loadChildren: props.loadChildren,
		})

		useTreeView({ isDisabled: toRef(props, 'isDisabled'), state })

		const theme = useComponentTheme<TreeViewRenderTheme>('TreeView')
		const { styles, config } = theme ?? defaultTreeViewTheme

		return () => {
			return wNodeToVue(
				renderTreeView(
					{
						visibleNodes: state.viewportNodes.value,
						selectionMode: state.selectionMode,
						hasScrollUp: state.hasScrollUp.value,
						hasScrollDown: state.hasScrollDown.value,
						scrollUpCount: state.scrollUpCount.value,
						scrollDownCount: state.scrollDownCount.value,
					},
					{ styles, config }
				)
			)
		}
	},
})
//#endregion Component

export {
	defaultTreeViewTheme as treeViewTheme,
	type TreeViewRenderTheme as TreeViewTheme,
}
export type { TreeViewProps as Props, TreeViewProps as IProps }
