// packages/solid/src/composables/use-json-viewer-state.ts
import { isDeepStrictEqual } from 'node:util'
import { createSignal, createMemo, createEffect, on } from 'solid-js'
import {
	jsonViewerReducer,
	createDefaultJsonViewerState,
	type JsonViewerState,
	type JsonViewerAction,
	type IJsonNode,
} from '@wolf-tui/shared'
import type { JsonViewerVisibleNode } from '@wolf-tui/shared'

//#region Types
export type UseJsonViewerStateProps = {
	/**
	 * Data to display. Can be any JSON-serializable value.
	 */
	data: unknown

	/**
	 * Default expand depth. Nodes at depth < this value are expanded on mount.
	 *
	 * @default 1
	 */
	defaultExpandDepth?: number

	/**
	 * Number of visible nodes in the viewport.
	 *
	 * @default 20
	 */
	visibleNodeCount?: number

	/**
	 * Maximum string length before truncation.
	 *
	 * @default 120
	 */
	maxStringLength?: number

	/**
	 * Whether to sort object keys alphabetically.
	 *
	 * @default false
	 */
	sortKeys?: boolean

	/**
	 * Maximum nesting depth.
	 *
	 * @default 100
	 */
	maxDepth?: number
}

export type JsonViewerStateResult = {
	data: unknown
	nodes: () => IJsonNode[]
	focusedIndex: () => number
	expandedIds: () => ReadonlySet<string>
	visibleNodes: () => JsonViewerVisibleNode[]
	hasScrollUp: () => boolean
	hasScrollDown: () => boolean
	indentWidth: () => number
	dispatch: (action: JsonViewerAction) => void
}
//#endregion Types

//#region Composable
export const useJsonViewerState = ({
	data,
	defaultExpandDepth,
	visibleNodeCount,
	maxStringLength,
	sortKeys,
	maxDepth,
}: UseJsonViewerStateProps): JsonViewerStateResult => {
	const initialState = createDefaultJsonViewerState({
		data,
		defaultExpandDepth,
		visibleNodeCount,
		maxStringLength,
		sortKeys,
		maxDepth,
	})

	const [state, setState] = createSignal<JsonViewerState>(initialState)

	const dispatch = (action: JsonViewerAction) => {
		setState((prev) => jsonViewerReducer(prev, action))
	}

	// Reset state when data changes
	const [lastData, setLastData] = createSignal(data)

	createEffect(
		on(
			() => JSON.stringify(data),
			() => {
				if (!isDeepStrictEqual(data, lastData())) {
					setState(
						createDefaultJsonViewerState({
							data,
							defaultExpandDepth,
							visibleNodeCount,
							maxStringLength,
							sortKeys,
							maxDepth,
						})
					)
					setLastData(data)
				}
			},
			{ defer: true }
		)
	)

	const nodes = createMemo(() => state().nodes)
	const focusedIndex = createMemo(() => state().focusedIndex)
	const expandedIds = createMemo(() => state().expandedIds)

	const visibleNodes = createMemo((): JsonViewerVisibleNode[] => {
		const s = state()
		const { nodes, viewport, focusedIndex, expandedIds } = s
		const fromIndex = viewport.fromIndex
		const toIndex = viewport.toIndex

		const visible: JsonViewerVisibleNode[] = []
		for (let i = fromIndex; i < toIndex && i < nodes.length; i++) {
			const node = nodes[i]!
			visible.push({
				node,
				isFocused: i === focusedIndex,
				isExpanded: expandedIds.has(node.id),
			})
		}

		return visible
	})

	const hasScrollUp = createMemo(() => state().viewport.fromIndex > 0)
	const hasScrollDown = createMemo(() => {
		const s = state()
		return s.viewport.toIndex < s.nodes.length
	})

	const indentWidth = createMemo(() => 2)

	return {
		data,
		nodes,
		focusedIndex,
		expandedIds,
		visibleNodes,
		hasScrollUp,
		hasScrollDown,
		indentWidth,
		dispatch,
	}
}
//#endregion Composable

// packages/react/src/components/JsonViewer/use-json-viewer-state.ts
import { isDeepStrictEqual } from 'node:util'
import {
	useReducer,
	useCallback,
	useMemo,
	useRef,
	useEffect,
	useState,
} from 'react'
import {
	jsonViewerReducer,
	createDefaultJsonViewerState,
	type IJsonNode,
} from '@wolf-tui/shared'

//#region Types
export type IUseJsonViewerStateProps = {
	/**
	 * Data to display.
	 */
	data: unknown

	/**
	 * Depth to expand by default.
	 *
	 * @default 1
	 */
	defaultExpandDepth?: number

	/**
	 * Number of visible nodes in the viewport.
	 *
	 * @default 20
	 */
	visibleNodeCount?: number

	/**
	 * Maximum string length before truncation.
	 *
	 * @default 120
	 */
	maxStringLength?: number

	/**
	 * Sort object keys alphabetically.
	 *
	 * @default false
	 */
	sortKeys?: boolean

	/**
	 * Callback when a node is selected (Enter key).
	 */
	onSelect?: (path: string, value: unknown) => void
}

export type IJsonViewerState = {
	data: unknown
	nodes: IJsonNode[]
	focusedIndex: number
	expandedIds: ReadonlySet<string>
	viewportFrom: number
	viewportTo: number
	visibleNodes: IJsonNode[]

	focusNext: () => void
	focusPrevious: () => void
	focusFirst: () => void
	focusLast: () => void
	expand: () => void
	collapse: () => void
	toggleExpand: () => void
	expandAll: () => void
	collapseAll: () => void
	moveToFirstChild: () => void
}
//#endregion Types

//#region Hook
export function useJsonViewerState({
	data,
	defaultExpandDepth = 1,
	visibleNodeCount = 20,
	maxStringLength = 120,
	sortKeys = false,
	onSelect: _onSelect,
}: IUseJsonViewerStateProps): IJsonViewerState {
	const [state, dispatch] = useReducer(
		jsonViewerReducer,
		{ data, defaultExpandDepth, visibleNodeCount, maxStringLength, sortKeys },
		createDefaultJsonViewerState
	)

	// Reset state when data changes
	const [lastData, setLastData] = useState(data)

	if (data !== lastData && !isDeepStrictEqual(data, lastData)) {
		dispatch({
			type: 'reset',
			state: createDefaultJsonViewerState({
				data,
				defaultExpandDepth,
				visibleNodeCount,
				maxStringLength,
				sortKeys,
			}),
		})
		setLastData(data)
	}

	const prevFocusedRef = useRef(state.focusedIndex)

	// Track focus changes for potential callback use
	useEffect(() => {
		prevFocusedRef.current = state.focusedIndex
	}, [state.focusedIndex])

	const focusNext = useCallback(() => {
		dispatch({ type: 'focus-next' })
	}, [])

	const focusPrevious = useCallback(() => {
		dispatch({ type: 'focus-previous' })
	}, [])

	const focusFirst = useCallback(() => {
		dispatch({ type: 'focus-first' })
	}, [])

	const focusLast = useCallback(() => {
		dispatch({ type: 'focus-last' })
	}, [])

	const expand = useCallback(() => {
		dispatch({ type: 'expand' })
	}, [])

	const collapse = useCallback(() => {
		dispatch({ type: 'collapse' })
	}, [])

	const toggleExpand = useCallback(() => {
		dispatch({ type: 'toggle-expand' })
	}, [])

	const expandAll = useCallback(() => {
		dispatch({ type: 'expand-all' })
	}, [])

	const collapseAll = useCallback(() => {
		dispatch({ type: 'collapse-all' })
	}, [])

	const moveToFirstChild = useCallback(() => {
		dispatch({ type: 'move-to-first-child' })
	}, [])

	const visibleNodes = useMemo(() => {
		return state.nodes.slice(state.viewport.fromIndex, state.viewport.toIndex)
	}, [state.nodes, state.viewport.fromIndex, state.viewport.toIndex])

	return {
		data: state.data,
		nodes: state.nodes,
		focusedIndex: state.focusedIndex,
		expandedIds: state.expandedIds,
		viewportFrom: state.viewport.fromIndex,
		viewportTo: state.viewport.toIndex,
		visibleNodes,
		focusNext,
		focusPrevious,
		focusFirst,
		focusLast,
		expand,
		collapse,
		toggleExpand,
		expandAll,
		collapseAll,
		moveToFirstChild,
	}
}
//#endregion Hook
