// packages/solid/src/components/Gradient.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import {
	renderGradient,
	defaultGradientTheme,
	type GradientRenderTheme,
	type GradientName,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export interface IGradientProps {
	children: JSX.Element
	name?: GradientName
	colors?: string[]
}
//#endregion Types

export function Gradient(props: IGradientProps): JSX.Element {
	const [local] = splitProps(props, ['children', 'name', 'colors'])

	const theme = useComponentTheme<GradientRenderTheme>('Gradient')

	const wnode = createMemo(() => {
		const text = String(local.children ?? '')
		return renderGradient(
			{ text, name: local.name, colors: local.colors },
			theme ?? defaultGradientTheme
		)
	})

	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}

// packages/react/src/components/Gradient/Gradient.tsx
import { type ReactNode } from 'react'
import {
	renderGradient,
	defaultGradientTheme,
	type GradientRenderTheme,
	type GradientName,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../../theme/theme'
import { wNodeToReact } from '../../wnode/wnode-to-react'

//#region Types
export type IGradientProps = {
	/**
	 * Text to paint with the gradient.
	 */
	children: ReactNode

	/**
	 * Named gradient preset.
	 *
	 * @default "rainbow"
	 */
	name?: GradientName

	/**
	 * Custom gradient stops (overrides `name` when provided).
	 */
	colors?: string[]
}
//#endregion Types

//#region Component
export function Gradient({ children, name, colors }: IGradientProps) {
	const theme = useComponentTheme<GradientRenderTheme>('Gradient')
	const { styles } = theme ?? defaultGradientTheme

	// Extract string text — Gradient paints plain text, not arbitrary nodes.
	const text = typeof children === 'string' ? children : String(children ?? '')

	return wNodeToReact(renderGradient({ text, name, colors }, { styles }))
}
//#endregion Component
