// packages/solid/src/components/ScrollView.tsx
import {
	type JSX,
	createSignal,
	createMemo,
	createEffect,
	splitProps,
	on,
} from 'solid-js'
import type { Styles } from '@wolf-tui/core'
import { measureElement } from '@wolf-tui/core'
import {
	clampScrollOffset,
	getBottomOffset,
	type IScrollMetrics,
} from '@wolf-tui/shared'
import { useInput } from '../composables/use-input'
import { resolveClassName, type ClassNameValue } from '../styles'

//#region Types
export interface IScrollViewHandle {
	scrollTo: (offset: number) => void
	scrollBy: (delta: number) => void
	scrollToTop: () => void
	scrollToBottom: () => void
	getScrollOffset: () => number
	getContentHeight: () => number
	getViewportHeight: () => number
}

export interface IScrollViewProps {
	/**
	 * Viewport height in terminal rows.
	 *
	 * Content above this height is clipped by the outer box.
	 */
	height: number

	/**
	 * Controlled scroll offset (in rows). If provided, the component becomes
	 * controlled — onScroll must be used to update the parent's state in
	 * response to keyboard input.
	 */
	offset?: number

	/**
	 * Whether to install default keyboard bindings (arrows, PageUp/Down,
	 * Home/End).
	 *
	 * @default true
	 */
	keyBindings?: boolean

	/**
	 * Fires whenever the internal or controlled offset would change.
	 *
	 * In controlled mode, parent must persist the new offset via `offset` prop.
	 */
	onScroll?: (offset: number) => void

	/**
	 * Fires when the measured inner content height changes.
	 */
	onContentHeightChange?: (height: number) => void

	/**
	 * Extra style applied to the outer (clipping) box.
	 */
	style?: Styles

	/**
	 * className applied to the outer (clipping) box.
	 */
	className?: ClassNameValue

	/**
	 * Ref callback receiving an imperative handle for programmatic scrolling.
	 */
	ref?: (handle: IScrollViewHandle) => void

	children?: JSX.Element
}
//#endregion Types

//#region Component
export function ScrollView(props: IScrollViewProps): JSX.Element {
	const [local] = splitProps(props, [
		'height',
		'offset',
		'keyBindings',
		'onScroll',
		'onContentHeightChange',
		'style',
		'className',
		'ref',
		'children',
	])

	// WHY: internal offset is the source of truth in uncontrolled mode;
	// in controlled mode (local.offset !== undefined) we read from props
	// directly via resolvedOffset() below.
	const [internalOffset, setInternalOffset] = createSignal(0)
	const [contentHeight, setContentHeight] = createSignal(0)

	const isControlled = () => local.offset !== undefined

	const resolvedOffset = createMemo(() =>
		isControlled() ? (local.offset ?? 0) : internalOffset()
	)

	const viewportHeight = () => local.height

	const metrics = (): IScrollMetrics => ({
		contentHeight: contentHeight(),
		viewportHeight: viewportHeight(),
	})

	// WHY: single funnel so uncontrolled mutation and keyboard input clamp
	// against the same metrics; controlled mode only notifies the parent.
	const commitOffset = (next: number) => {
		const clamped = clampScrollOffset(next, metrics())
		if (!isControlled()) {
			setInternalOffset(clamped)
		}
		local.onScroll?.(clamped)
	}

	// WHY: store the inner DOM element so we can measure it after layout.
	// The ref callback fires synchronously during node attachment — BEFORE
	// calculateLayout runs — so measureElement would return 0. We keep the
	// element and re-measure on each scheduled render pass via a microtask
	// that runs after the layout phase has populated Taffy's computed layout.
	const [innerEl, setInnerEl] = createSignal<
		Parameters<typeof measureElement>[0] | null
	>(null)

	const innerRefCallback = (el: unknown) => {
		if (!el || typeof el !== 'object') return
		setInnerEl(el as Parameters<typeof measureElement>[0])
	}

	// WHY: defer measurement until after the render scheduler's flush
	// (calculateLayout + coreRenderer). `queueMicrotask` inside the effect
	// schedules the read on the next microtask tick — by then Taffy has
	// populated the inner box's computed layout. Mirrors React's measure-
	// in-render pattern, where re-measurement loops via state → re-render.
	createEffect(() => {
		const el = innerEl()
		if (!el) return
		// Re-run measurement on every offset change — cheap, and guarantees
		// that children-driven height changes propagate.
		resolvedOffset()
		queueMicrotask(() => {
			const dims = measureElement(el)
			if (dims.height !== contentHeight()) {
				setContentHeight(dims.height)
			}
		})
	})

	// WHY: notify parent on content-height changes. `on(..., { defer: true })`
	// skips the initial 0-height render so we don't fire a spurious callback.
	createEffect(
		on(
			contentHeight,
			(h) => {
				local.onContentHeightChange?.(h)
			},
			{ defer: true }
		)
	)

	// WHY: if content shrinks below current offset, re-clamp (uncontrolled only).
	createEffect(() => {
		const h = contentHeight()
		if (!isControlled()) {
			const current = internalOffset()
			const clamped = clampScrollOffset(current, {
				contentHeight: h,
				viewportHeight: viewportHeight(),
			})
			if (clamped !== current) {
				setInternalOffset(clamped)
				local.onScroll?.(clamped)
			}
		}
	})

	//#region Imperative Handle
	const handle: IScrollViewHandle = {
		scrollTo: (offset) => commitOffset(offset),
		scrollBy: (delta) => commitOffset(resolvedOffset() + delta),
		scrollToTop: () => commitOffset(0),
		scrollToBottom: () => commitOffset(getBottomOffset(metrics())),
		getScrollOffset: () => resolvedOffset(),
		getContentHeight: () => contentHeight(),
		getViewportHeight: () => viewportHeight(),
	}

	// WHY: invoke the ref callback once; Solid's ref prop handling unwraps
	// the function form for us on intrinsic elements, but for an imperative
	// handle we call it explicitly.
	if (local.ref) {
		local.ref(handle)
	}
	//#endregion Imperative Handle

	//#region Keyboard Bindings
	useInput(
		(_input, key) => {
			if (key.upArrow) {
				commitOffset(resolvedOffset() - 1)
				return
			}
			if (key.downArrow) {
				commitOffset(resolvedOffset() + 1)
				return
			}
			if (key.pageUp) {
				commitOffset(resolvedOffset() - viewportHeight())
				return
			}
			if (key.pageDown) {
				commitOffset(resolvedOffset() + viewportHeight())
				return
			}
			if (key.home) {
				commitOffset(0)
				return
			}
			if (key.end) {
				commitOffset(getBottomOffset(metrics()))
			}
		},
		{ isActive: () => (local.keyBindings ?? true) === true }
	)
	//#endregion Keyboard Bindings

	//#region Styles
	const outerStyle = (): Styles => {
		const userStyle = local.style ?? {}
		const resolved = resolveClassName(local.className)
		return {
			flexDirection: 'column',
			flexShrink: 0,
			...resolved,
			...userStyle,
			height: viewportHeight(),
			overflow: 'hidden',
		}
	}

	const innerStyle = (): Styles => ({
		flexDirection: 'column',
		flexShrink: 0,
		marginTop: -resolvedOffset(),
	})
	//#endregion Styles

	return (
		<wolfie-box style={outerStyle()}>
			<wolfie-box ref={innerRefCallback} style={innerStyle()}>
				{local.children}
			</wolfie-box>
		</wolfie-box>
	)
}
//#endregion Component

export type { IScrollViewProps as Props, IScrollViewProps as IProps }

// packages/react/src/components/ScrollView/index.tsx
import {
	forwardRef,
	useCallback,
	useEffect,
	useImperativeHandle,
	useState,
} from 'react'
import { measureElement, type DOMElement } from '@wolf-tui/core'
import { clampScrollOffset, computeBoxStyle } from '@wolf-tui/shared'
import { useInput } from '../../hooks/use-input'
import type { IScrollViewHandle, IScrollViewProps } from './types'

/**
`<ScrollView>` is a fixed-height viewport that clips its children and allows
scrolling through overflowing content. It uses a negative `marginTop` on an
inner box plus `overflow: hidden` on the outer box to scroll — no terminal
scrollback is involved.

Uncontrolled (internal state) usage:

```tsx
<ScrollView height={8}>
  {items.map((it) => <Text key={it.id}>{it.label}</Text>)}
</ScrollView>
```

Controlled usage:

```tsx
const [offset, setOffset] = useState(0)
<ScrollView height={8} offset={offset} onScroll={setOffset}>
  {...}
</ScrollView>
```

Imperative API via ref:

```tsx
const handle = useRef<IScrollViewHandle>(null)
handle.current?.scrollToBottom()
```
*/
export const ScrollView = forwardRef<IScrollViewHandle, IScrollViewProps>(
	function ScrollView(
		{
			height,
			offset: controlledOffset,
			keyBindings = true,
			onScroll,
			onContentHeightChange,
			className,
			style,
			children,
		},
		ref
	) {
		const isControlled = controlledOffset !== undefined
		const [internalOffset, setInternalOffset] = useState(0)
		const offset = isControlled ? controlledOffset : internalOffset

		const [contentHeight, setContentHeight] = useState(0)
		const [innerRef, setInnerRef] = useState<DOMElement | null>(null)

		// Measure the inner box on every render. Mirrors the measure pattern used
		// in ProgressBar (callback-ref + useState + measureElement).
		if (innerRef) {
			const dimensions = measureElement(innerRef)
			if (dimensions.height !== contentHeight) {
				setContentHeight(dimensions.height)
			}
		}

		// Notify parent when the measured content height changes.
		useEffect(() => {
			onContentHeightChange?.(contentHeight)
		}, [contentHeight, onContentHeightChange])

		// Stable setter that handles both controlled and uncontrolled modes and
		// always clamps against the current metrics.
		const applyOffset = useCallback(
			(next: number) => {
				const clamped = clampScrollOffset(next, {
					contentHeight,
					viewportHeight: height,
				})
				if (!isControlled) {
					setInternalOffset((prev) => (prev === clamped ? prev : clamped))
				}
				if (clamped !== offset) {
					onScroll?.(clamped)
				}
			},
			[contentHeight, height, isControlled, offset, onScroll]
		)

		// Imperative handle: scrollTo/By/Top/Bottom + getters.
		useImperativeHandle(
			ref,
			() => ({
				scrollTo: (next) => applyOffset(next),
				scrollBy: (delta) => applyOffset(offset + delta),
				scrollToTop: () => applyOffset(0),
				scrollToBottom: () => applyOffset(Number.MAX_SAFE_INTEGER),
				getScrollOffset: () => offset,
				getContentHeight: () => contentHeight,
				getViewportHeight: () => height,
			}),
			[applyOffset, offset, contentHeight, height]
		)

		// Built-in key bindings: arrows (1 row), PageUp/PageDown (viewport),
		// Home/End (extremes). All captured closure values appear in the effect
		// deps inside useInput — `applyOffset` + `offset` + `height`.
		useInput(
			(_input, key) => {
				if (key.upArrow) {
					applyOffset(offset - 1)
					return
				}
				if (key.downArrow) {
					applyOffset(offset + 1)
					return
				}
				if (key.pageUp) {
					applyOffset(offset - height)
					return
				}
				if (key.pageDown) {
					applyOffset(offset + height)
					return
				}
				if (key.home) {
					applyOffset(0)
					return
				}
				if (key.end) {
					applyOffset(Number.MAX_SAFE_INTEGER)
				}
			},
			{ isActive: keyBindings }
		)

		// Merge caller style/className via the shared compute helper, then force
		// the fixed-height clipping viewport invariants on top.
		const viewportStyle = {
			...computeBoxStyle({ className, style }),
			height,
			overflow: 'hidden' as const,
			overflowX: 'hidden' as const,
			overflowY: 'hidden' as const,
			flexDirection: 'column' as const,
		}

		return (
			<wolfie-box style={viewportStyle}>
				<wolfie-box
					ref={setInnerRef}
					style={{
						flexDirection: 'column',
						flexShrink: 0,
						marginTop: -offset,
					}}
				>
					{children}
				</wolfie-box>
			</wolfie-box>
		)
	}
)

ScrollView.displayName = 'ScrollView'

export type { IScrollViewProps, IScrollViewHandle } from './types'
