// packages/solid/src/composables/use-timer-state.ts
import { createSignal, createMemo, createEffect, on, onCleanup } from 'solid-js'
import {
	timerReducer,
	createInitialTimerState,
	formatTime,
	type TimerState,
	type TimerAction,
	type TimerVariant,
	type TimeFormat,
	type ILap,
} from '@wolf-tui/shared'

//#region Types
export type UseTimerStateProps = {
	/**
	 * Timer variant: 'timer' (count up), 'countdown', or 'stopwatch' (with laps).
	 *
	 * @default 'timer'
	 */
	variant?: TimerVariant

	/**
	 * Duration in milliseconds (used for countdown).
	 *
	 * @default 0
	 */
	durationMs?: number

	/**
	 * Whether the timer starts automatically.
	 *
	 * @default true
	 */
	autoStart?: boolean

	/**
	 * Tick interval in milliseconds.
	 *
	 * @default 1000
	 */
	interval?: number

	/**
	 * Prefix text displayed before the time.
	 */
	prefix?: string

	/**
	 * Suffix text displayed after the time.
	 */
	suffix?: string

	/**
	 * Time display format.
	 *
	 * @default 'digital'
	 */
	format?: TimeFormat

	/**
	 * Called when the timer completes (countdown only).
	 */
	onComplete?: () => void

	/**
	 * Called on each tick with the current elapsed milliseconds.
	 */
	onTick?: (elapsedMs: number) => void

	/**
	 * Called when a new lap is recorded (stopwatch only).
	 */
	onLap?: (lap: ILap) => void
}

export type TimerStateResult = {
	formattedTime: () => string
	isRunning: () => boolean
	isPaused: () => boolean
	isComplete: () => boolean
	elapsedMs: () => number
	laps: () => readonly ILap[]
	variant: () => TimerVariant
	dispatch: (action: TimerAction) => void
}
//#endregion Types

//#region Composable
export const useTimerState = ({
	variant = 'timer',
	durationMs = 0,
	autoStart = true,
	interval = 1000,
	format = 'digital',
	prefix,
	suffix,
	onComplete,
	onTick,
	onLap,
}: UseTimerStateProps): TimerStateResult & {
	prefix?: string
	suffix?: string
} => {
	const initialState = createInitialTimerState({
		variant,
		durationMs,
		autoStart,
	})
	const [state, setState] = createSignal<TimerState>(initialState)

	const dispatch = (action: TimerAction) => {
		setState((prev) => {
			const next = timerReducer(prev, action)
			if (!prev.isComplete && next.isComplete) {
				onComplete?.()
			}
			if (action.type === 'lap' && next.laps.length > prev.laps.length) {
				const newLap = next.laps[next.laps.length - 1]
				if (newLap) {
					onLap?.(newLap)
				}
			}
			return next
		})
	}

	// Reset state when variant or durationMs changes
	createEffect(
		on(
			() => ({ variant, durationMs }),
			(
				newProps: { variant: TimerVariant; durationMs: number | undefined },
				oldProps:
					| { variant: TimerVariant; durationMs: number | undefined }
					| undefined
			) => {
				if (
					oldProps !== undefined &&
					(newProps.variant !== oldProps.variant ||
						newProps.durationMs !== oldProps.durationMs)
				) {
					stopInterval()
					setState(
						createInitialTimerState({
							variant: newProps.variant,
							durationMs: newProps.durationMs,
							autoStart,
						})
					)
				}
			},
			{ defer: true }
		)
	)

	//#region Interval Management
	let intervalId: ReturnType<typeof setInterval> | undefined
	let lastTickTime = 0

	function startInterval() {
		if (intervalId !== undefined) return
		lastTickTime = Date.now()
		intervalId = setInterval(() => {
			const now = Date.now()
			const deltaMs = now - lastTickTime
			lastTickTime = now
			dispatch({ type: 'tick', deltaMs })
			onTick?.(state().elapsedMs)
		}, interval)
	}

	function stopInterval() {
		if (intervalId !== undefined) {
			clearInterval(intervalId)
			intervalId = undefined
		}
	}

	const isRunning = createMemo(() => state().isRunning)

	// Track only isRunning changes -- interval must not restart on every tick
	createEffect(() => {
		if (isRunning()) {
			startInterval()
		} else {
			stopInterval()
		}
	})

	onCleanup(() => stopInterval())
	//#endregion Interval Management

	const formattedTime = createMemo(() => {
		const s = state()
		const ms =
			s.variant === 'countdown'
				? Math.max(0, s.durationMs - s.elapsedMs)
				: s.elapsedMs

		if (typeof format === 'function') {
			return format(ms)
		}

		return formatTime(ms, format).text
	})
	const isPaused = createMemo(
		() => !state().isRunning && state().elapsedMs > 0 && !state().isComplete
	)
	const isComplete = createMemo(() => state().isComplete)
	const elapsedMs = createMemo(() => state().elapsedMs)
	const laps = createMemo(() => state().laps)
	const variantSignal = createMemo(() => state().variant)

	return {
		formattedTime,
		isRunning,
		isPaused,
		isComplete,
		elapsedMs,
		laps,
		variant: variantSignal,
		dispatch,
		prefix,
		suffix,
	}
}
//#endregion Composable

// packages/react/src/components/Timer/use-timer-state.ts
import { useReducer, useCallback, useEffect, useRef, useState } from 'react'
import {
	timerReducer,
	createInitialTimerState,
	formatTime,
	type TimerState,
	type TimerAction,
	type TimerVariant,
	type ILap,
	type IFormattedTime,
	type TimeFormat,
} from '@wolf-tui/shared'

//#region Extended Reducer
type ExtendedTimerAction = TimerAction | { type: 'reinit'; state: TimerState }

const extendedTimerReducer = (
	state: TimerState,
	action: ExtendedTimerAction
): TimerState => {
	if (action.type === 'reinit') {
		return action.state
	}
	return timerReducer(state, action)
}
//#endregion Extended Reducer

//#region Types
export type IUseTimerStateProps = {
	/**
	 * Timer variant: 'timer' (count up), 'countdown', or 'stopwatch' (with laps).
	 *
	 * @default 'timer'
	 */
	variant?: TimerVariant

	/**
	 * Start the timer automatically on mount.
	 *
	 * @default true
	 */
	autoStart?: boolean

	/**
	 * Tick interval in milliseconds.
	 *
	 * @default 1000
	 */
	interval?: number

	/**
	 * Time display format.
	 *
	 * @default 'digital'
	 */
	format?: TimeFormat

	/**
	 * Total duration for countdown variant (milliseconds).
	 */
	durationMs?: number

	/**
	 * Callback fired on each tick with elapsed milliseconds.
	 */
	onTick?: (elapsedMs: number) => void

	/**
	 * Callback fired when countdown completes.
	 */
	onComplete?: () => void

	/**
	 * Callback fired when a new lap is recorded (stopwatch only).
	 */
	onLap?: (lap: ILap) => void
}

export type ITimerState = {
	elapsedMs: number
	isRunning: boolean
	isComplete: boolean
	laps: readonly ILap[]
	formatted: IFormattedTime

	start: () => void
	stop: () => void
	toggle: () => void
	reset: () => void
	restart: () => void
	lap: () => void
}
//#endregion Types

//#region Hook
export function useTimerState({
	variant = 'timer',
	autoStart = true,
	interval = 1000,
	format = 'digital',
	durationMs,
	onTick,
	onComplete,
	onLap,
}: IUseTimerStateProps): ITimerState {
	const [state, dispatch] = useReducer(
		extendedTimerReducer,
		{ variant, durationMs, autoStart },
		createInitialTimerState
	)

	// Reset state when variant or durationMs changes
	const [lastVariant, setLastVariant] = useState(variant)
	const [lastDurationMs, setLastDurationMs] = useState(durationMs)

	if (variant !== lastVariant || durationMs !== lastDurationMs) {
		dispatch({
			type: 'reinit',
			state: createInitialTimerState({ variant, durationMs, autoStart }),
		})
		setLastVariant(variant)
		setLastDurationMs(durationMs)
	}

	const startedAtRef = useRef<number | undefined>(undefined)
	const accumulatedRef = useRef(0)
	const intervalIdRef = useRef<ReturnType<typeof setInterval> | undefined>(
		undefined
	)
	const prevElapsedRef = useRef(state.elapsedMs)
	const prevLapsLengthRef = useRef(state.laps.length)
	const prevIsCompleteRef = useRef(state.isComplete)

	// Start/stop the interval based on isRunning
	useEffect(() => {
		if (state.isRunning) {
			startedAtRef.current = Date.now()
			accumulatedRef.current = state.elapsedMs

			intervalIdRef.current = setInterval(() => {
				const now = Date.now()
				const deltaMs = now - (startedAtRef.current ?? now)
				const totalElapsed = accumulatedRef.current + deltaMs
				dispatch({
					type: 'tick',
					deltaMs: totalElapsed - accumulatedRef.current,
				})
				accumulatedRef.current = totalElapsed
				startedAtRef.current = now
			}, interval)

			return () => {
				if (intervalIdRef.current !== undefined) {
					clearInterval(intervalIdRef.current)
					intervalIdRef.current = undefined
				}
			}
		}

		// Not running -- clear any existing interval
		if (intervalIdRef.current !== undefined) {
			clearInterval(intervalIdRef.current)
			intervalIdRef.current = undefined
		}

		return undefined
	}, [state.isRunning, interval])

	// onTick callback
	useEffect(() => {
		if (state.elapsedMs !== prevElapsedRef.current) {
			prevElapsedRef.current = state.elapsedMs
			onTick?.(state.elapsedMs)
		}
	}, [state.elapsedMs, onTick])

	// onComplete callback
	useEffect(() => {
		if (state.isComplete && !prevIsCompleteRef.current) {
			onComplete?.()
		}
		prevIsCompleteRef.current = state.isComplete
	}, [state.isComplete, onComplete])

	// onLap callback
	useEffect(() => {
		if (state.laps.length > prevLapsLengthRef.current) {
			const latestLap = state.laps[state.laps.length - 1]
			if (latestLap) {
				onLap?.(latestLap)
			}
		}
		prevLapsLengthRef.current = state.laps.length
	}, [state.laps, onLap])

	const start = useCallback(() => {
		dispatch({ type: 'start' })
	}, [])

	const stop = useCallback(() => {
		dispatch({ type: 'stop' })
	}, [])

	const toggle = useCallback(() => {
		dispatch({ type: 'toggle' })
	}, [])

	const reset = useCallback(() => {
		dispatch({ type: 'reset' })
	}, [])

	const restart = useCallback(() => {
		dispatch({ type: 'restart' })
	}, [])

	const lap = useCallback(() => {
		dispatch({ type: 'lap' })
	}, [])

	const displayMs =
		variant === 'countdown' && durationMs !== undefined
			? Math.max(0, durationMs - state.elapsedMs)
			: state.elapsedMs

	const formatted = formatTime(displayMs, format)

	return {
		elapsedMs: state.elapsedMs,
		isRunning: state.isRunning,
		isComplete: state.isComplete,
		laps: state.laps,
		formatted,
		start,
		stop,
		toggle,
		reset,
		restart,
		lap,
	}
}
//#endregion Hook
